testing-library/dom-testing-library

- src/__tests__/element-queries.js
- src/jest-extensions.js
(re-creating https://github.com/kentcdodds/react-testing-library/pull/46)
This is a proposed refactor to the custom matchers code, as briefly discussed in https://github.com/kentcdodds/react-testing-library/pull/44#discussion_r179593891:
Closes #45
> Refactor custom matchers

- README.md
- src/__tests__/element-queries.js
- src/extend-expect.js
- src/jest-extensions.js
As discussed in #2 (closes #2)
One thing to note about it: I did this custom matcher so that it can even be used to match more than one class at the same time:
```javascript
// <button data-testid="delete-button" class="btn extra btn-danger">
//   Delete item
// </button>
// This passes, even though `"btn btn-danger"` are not contiguous in the actual class attr
expect(getByTestId('delete-button')).toHaveClass('btn btn-danger')
```
I think this makes it much more useful, and was not difficult to support.
> Add toHaveClass custom matcher (closes #2)

- README.md
- package.json
- src/__tests__/__snapshots__/element-queries.js.snap
- src/__tests__/element-queries.js
- src/queries.js
Fix for https://github.com/kentcdodds/react-testing-library/issues/31
@kentcdodds Let me know if things are good to go!
> feat(debug_helper): Adding debug helper when a get call fails

- README.md
This is most probably a remnant of when this lib was extracted from react-testing-library
> Replace reference to react specific tests

- package.json
Ran in to this error while trying to install with yarn
```
error dom-testing-library@1.8.0: The engine "node" is incompatible with this module. Expected version "> 6".
```
Ran with 
Node: 6.11.2
Yarn: 1.3.2
> Allow node >=6

- README.md
- src/__tests__/element-queries.js
- src/__tests__/matches.js
- src/matches.js
- src/queries.js
[fixes #8]
**What**:
**Why**:
**How**:
**Checklist**:
> fix: use exact match for data-testid

- README.md
- src/__tests__/__snapshots__/element-queries.js.snap
- src/__tests__/element-queries.js
- src/queries.js
**What**:
Add ability to get/query by title, basic test coverage for now
**Why**:
Here comes my question, I've been seeing this pattern quite a bit:
https://github.com/meteor/todos/blob/react/imports/ui/components/ListHeader.jsx#L162
I wanted to learn your thinking here - are those antipatterns? I'm rewriting above example app by the Meteor guys to Apollo backend/frontend, while using cypress-testing-library and react-testing-library to drive the work.
I'm not sure if I have any other way of accessing elements like that.
I could rewrite places like that to use img with alt instead, but I'm trying to keep the components as similar to the original ones as possible (so it will be easier to compare between meteor and apollo)
**How**:
**Checklist**:
> poc for getting/querying by title

- .all-contributorsrc
- README.md
**What**:
Update the docs to reflect the possibility of specifying a selector for some functions.
**Why**:
https://github.com/kentcdodds/dom-testing-library/issues/47
**Checklist**:
> chore: update documentation

- .all-contributorsrc
- README.md
- src/index.js
**What**: Add a `within` API
**Why**: Kindly see #53 
**How**: Exported `getQueriesForElement` as `within` from the index.js file
**Checklist**:
> Add within API #53

- src/index.js
- src/queries.js
- src/query-helpers.js
- typings/index.d.ts
- typings/queries.d.ts
- typings/query-helpers.d.ts
These are useful for creating additional queries outside the library
**What**:
**Why**:
**How**:
**Checklist**:
> feat(queries): expose helper functions

- src/__tests__/get-queries-for-element.js
- src/get-queries-for-element.js
- typings/get-queries-for-element.d.ts
**What**:
**Why**:
**How**:
**Checklist**:
> feat(queries): allow overriding queries in getQueriesForElement

- README.md
- extend-expect.js
- package.json
**What**:
Remove extend-expect from this library.
**Why**:
Users should directly import the same functionality from jest-dom
**How**:
Removing the file and changing the documentation around it, and its reference from package.json
**Checklist**:
Closes #69
> Use extend-expect directly from jest-dom

- README.md
**What**:
This PR adds a reference to another implementation of this library for use with puppeteer.
**Why**:
To have consistent integration test style when using puppeteer.
**How**:
Inject dom-testing-library into the page and proxy all method requests to it. See https://github.com/patrickhulce/pptr-testing-library :)
**Checklist**:
Thanks for the library, love it :)
> docs: add pptr-testing-library link

- src/get-node-text.js
- src/wait-for-element.js
fix: Reference Node and MutationObserver off of the window object rather than globally
You have to handle shims yourself if not using jest without this
**What**:
Changes references to `Node` and `MutationObserver` to use `window` rather than globally.
**Why**:
The polyfills/shims do not work in a non-jest environment
**How**:
`Node` -> `window.Node`
`MutationObserver` -> `window.MutationObserver`
**Checklist**:
> fix: Reference Node and MutationObserver off of the window object

- README.md
**What**:
Added Using Without Jest docs section
**Why**:
There is setup required.
**How**:
Edited the readme
**Checklist**:
> docs: added Using Without Jest section

- README.md
**What**: Use getByText instead of getElementByText in a code example, which seems like it was a typo.
**Why**: getElementByText is not exported by dom-testing-library as far as I'm aware, which could be confusing.
**Checklist**:
> Replace getElementByText with getByText

- README.md
- src/__tests__/events.js
- src/events.js
**What**: feat(fireEvent): helper to assign target properties to node
**Why**: Specifically this is so the change event can set the value of the node
in a way that works for React (and all other frameworks and
non-frameworks) nicely.
fixes: https://github.com/kentcdodds/react-testing-library/issues/152
**How**: Add some logic to the `fireEvent` utility, and borrow some code from a thread in react issues.
**Checklist**:
> feat(fireEvent): helper to assign target properties to node

- README.md
- src/__tests__/events.js
- src/events.js
**What**: feat(events): allow setting the files value in change events
**Why**:
Similar to the value, this works around limitations with DOM properties that make testing certain use cases harder. This simplifies those cases
**How**:
Add another condition in the fireEvent handler
**Checklist**:
> feat(events): allow setting the files value in change events

- package.json
**What**:
Dep upgrade
**Why**:
I noticed I got both 0.4.0 and 1.0.0 in my lockfile when installing react-testing-library
**How**:
GitHub UI
**Checklist**:
> fix: upgrade wait-for-expect to 1.0.0

- src/__tests__/wait-for-element.js
- src/wait-for-element.js
**What**: #99 waitForElement gets into infinite setTimeout loop
**Why**: without the change MutationObserver gets into infinite setTimeout loop
**How**: disconnect the MutationObserver from setImmediate callback to ensure we're not in MutationObserver's `onMutate` callback when disconnecting it.
**Checklist**:
> Ensure waitForElement disconnects MutationObserver at the right time

- README.md
**What**:
Change code section boundary to the proper place.
**Why**:
Some text meant to be part of markdown was incorrectly being rendered as part of a code section.
**Checklist**:
> Minor fix to README markdown

- .all-contributorsrc
- .size-snapshot.json
- README.md
- src/__tests__/__snapshots__/element-queries.js.snap
- src/__tests__/element-queries.js
- src/__tests__/text-matchers.js
- src/queries.js
- typings/queries.d.ts
**What**: 
Add methods to access a `<select>` element by its selected option's text value. 
**Why**:
The first `<option>` is commonly used in `<select>` elements, like a placeholder attribute is used for text inputs. What the user sees is the text value of the first option, but it's not possible to access the `<select>` element given that text value. This PR provides methods to access the `<select>` element in that situation. Closes #104.
**How**:
`queryBySelectText()`, `queryAllBySelectText()`, `getBySelectText()`, and `getAllBySelectText()` were implemented.
**Checklist**:
Thank you for making an excellent testing library. Happy to be contributing! 😄
>  feat(queryBySelectText): add get/query by select text

- README.md
- src/__tests__/element-queries.js
- src/queries.js
**What**: add `ignore` option to `*ByText` which defaults to `'script'`
**Why**:
In our app at PayPal we're testing with Cypress and our localization content is set in a script tag on the page when it's rendered by the server. When using `getByText` with `cypress-testing-library`, we were getting that script tag before the app had a chance to render.
I'm pretty confident that 99.999% of the time people wont want to get a script tag with `getByText`, so the default makes sense to me.
**How**:
Added another layer of filtering to `queryAllByText` to filter nodes which return true for `.matches(ignore)`. Feel pretty flexible. Happy that DOM API exists!
**Checklist**:
> feat(getByText): add ignore option which defaults to `'script'`

- package.json
**What**:
Upgrade `pretty-format` to latest major.
**Why**:
It supports formatting `DocumentFragment`, which is nice if you don't need a full DOM (or don't want to wrap things in a `div` for a snapshot). See https://github.com/facebook/jest/pull/6705
**How**:
Bumped in package.json
**Checklist**:
> fix: upgrade pretty-format

- .size-snapshot.json
- README.md
- src/__tests__/element-queries.js
- src/queries.js
Fixes #120 
**What**:
**Why**:
**How**:
**Checklist**:
> feat(labels): add support for aria-labelledby

- src/queries.js
**What**:
Replace the existing select query mechanism which uses `HTMLSelectElement .selectedOptions` with a query that searches for the `selected` attribute of an `HTMLOptionElement`.
**Why**:
Closes #115.
Since `selectedOptions` is not a reactive property, JSDOM was not updating to match the selected option in a select Element. The `selected` attribute is reactive.
**How**:
Instead of iterating through `selectedOptions` of an HTMLSelectElement, we iterate through all HTMLSelectOptions and isolate the ones that are selected.
I've gone ahead and tested this locally to make sure that it would be reactive! 👍 
**Checklist**:
> Have queryAllBySelectText query using reactive properties

- .size-snapshot.json
- jest.config.js
- package.json
- src/__tests__/__snapshots__/wait-for-element.js.snap
- src/__tests__/element-queries.js
- src/__tests__/events.js
- src/__tests__/example.js
- src/__tests__/get-queries-for-element.js
- src/__tests__/helpers/document.js
- src/__tests__/helpers/test-utils.js
- src/__tests__/pretty-dom.js
- src/__tests__/wait-for-dom-change.js
- src/__tests__/wait-for-element.js
- src/__tests__/wait.js
- src/events.js
- src/get-node-text.js
- src/query-helpers.js
- src/wait-for-dom-change.js
- src/wait-for-element.js
This PR supersedes #119, incorporates all your changes, checks if window.MutationObserver is available and uses it instead of using mock, and takes care of wait-for-dom-change
> Allow for running in node environment

- .size-snapshot.json
- src/__tests__/helpers.js
- src/helpers.js
- src/wait-for-dom-change.js
- src/wait-for-element.js
This fixes code coverage of #125 by extracting helper functions.
There are still few istanbul ignores in code but they are not mine :)
> Fix code coverage for node env changes

- src/__tests__/element-queries.js
- src/__tests__/helpers/test-utils.js
- src/query-helpers.js
Fixes an unsafe reference that can throw an error in `debugDOM` when it receives a reference to a `document` in a real browser (ie puppeteer/codepen)
**What**:
**Why**:
**How**:
**Checklist**:
> fix: unsafe attribute reference

- typings/queries.d.ts
fixes #142
**What**:
**Why**:
**How**:
**Checklist**:
> fix(types): fix types for bound attribute queries

- README.md
- show the much-asked-for data-test-id override as the default example
- use commonjs module syntax due to a babel 6 issue with overwriting named exports (not present in v7)
**What**:
**Why**:
**How**:
**Checklist**:
> docs: add custom query example

- .travis.yml
- package.json
**What**:
All supported Node.js versions should be tested to catch any issues on newer LTS releases.
**Why**:
To ensure that there are no breaking builds on Node.js 6, 10 and 11.
**How**:
Updated the Travis CI config.
**Checklist**:
> ci: test Node.js 8, 10 and 11

- typings/events.d.ts
**What**: Update typescript types to allow for `Element` (instead of `HTMLElement`) to be used in event functions.
**Why**: Browser APIs such as `querySelector` returns `Element`, not `HTMLElement`. This requires an explicit cast to use the event functions from `dom-testing-library`.
**How**: Updated typescript definitions.
**Checklist**:
Resolves #149
> Make event functions accept Element

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_Report.md
**What**:
**Why**:
**How**:
**Checklist**:
> add link to minimal bug report repo in templates

- README.md
Added a new paragraph which calls out the helper library `user-event`
**What**:
Updated the README file to callout the `user-event`-library
**Why**:
A useful library which eases to apply common user interactions with components, such as typing, clicking buttons.
**Checklist**:
> Updated README.md to callout `user-event`

- typings/index.d.ts
**What**:
TypeScript typings were added for `waitForDomChange` in #117 but were never linked to from index.d.ts.
**Why**:
Without this change, `waitForDomChange` isn't accessible from TypeScript code, and the TS typings for the function are wasted.
**Checklist**:
> fix(waitForDomChange): fix link to TS types

- typings/events.d.ts
**What**:
Add typings for the new focusin/focusout events
**Why**:
Enables the new API to be used from TypeScript
**Checklist**:
> fix(TS): add focusin/focusout typings

- src/__tests__/element-queries.js
- src/queries.js
> allow queryAllByText to select text nodes text content

- src/queries.js
Fixes https://github.com/kentcdodds/dom-testing-library/issues/215
**What**:
Fixes the error caused by loose mode transpilation as spotted by @lavigneer:
> No, there aren't any elements in that `NodeList` that are also a `NodeList`
> 
> I just tested wrapping `container.querySelectorAll(selector)` explicitly in an `Array.from` call in the built `.esm` bundle and that appeared to resolve the issue.
> 
> The transpilation of
> `Array.from([...baseArray, ...container.querySelectorAll(selector)])`
> results in
> `Array.from([].concat(baseArray, container.querySelectorAll(selector)))`
> so it's not converting the `NodeList` to an array and is just trying to `concat` it directly
**Why**:
To fix regression
**How**:
Explicitly use `Array.from` to force the `NodeList` to be converted to an array …
> Fix node.matches is not a function

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_Report.md
- .github/ISSUE_TEMPLATE/Feature_Request.md
**What**:
**Why**:
**How**:
**Checklist**:
> docs: add link to docs site from issue templates

- src/__tests__/element-queries.js
- src/__tests__/example.js
- src/__tests__/helpers/test-utils.js
- src/__tests__/queries.find.js
- src/__tests__/text-matchers.js
- src/__tests__/wait-for-dom-change.js
- src/__tests__/wait-for-element-to-be-removed.fake-timers.js
- src/__tests__/wait-for-element-to-be-removed.js
- src/__tests__/wait-for-element.js
- src/queries.js
- src/query-helpers.js
- tests/setup-env.js
**What**: add findBy* query type
**Why**: Closes #203
**How**: Created a simple `makeFinder` function and made a finder for every query type based on the getBy queries
**Checklist**:
> feat(findBy*): adds findBy* query type allowing for async element queries

- src/get-node-text.js
- src/queries.js
- src/wait-for-element.js
- typings/get-queries-for-element.d.ts
**What**: fix(ByLabel): use getNodeText abstraction instead of textContent
**Why**: Closes #190
**How**: Make `queryAllByLabelText` use `getNodeText` instead of `textContent`
Also, I formatted everything 🤷‍♂️ 
**Checklist**:
> fix(ByLabel): use getNodeText abstraction instead of textContent

- src/__tests__/__snapshots__/element-queries.js.snap
- src/__tests__/element-queries.js
- src/__tests__/text-matchers.js
- src/queries.js
- typings/queries.d.ts
**What**: fix: remove deprecated queries
**Why**: Closes #223
**How**: Removed the queries and updated tests for those old queries to use the newer `ByDisplayValue` variant.
**Checklist**:
BREAKING CHANGE: This removes the deprecated queries `ByValue` and `BySelectText`. Use `ByDisplayValue` instead.
> fix: remove deprecated queries

- src/config.js
- src/wait-for-dom-change.js
- src/wait-for-element-to-be-removed.js
- src/wait-for-element.js
- src/wait.js
- typings/config.d.ts
**What**: add asyncWrapper config
**Why**: At first glance you're probably thinking: "Oh no, no no. No way." But think for a moment that react-testing-library can't just export its own `wait*` APIs and make everything work, because the `findBy*` queries all use the `waitForElement` API that's exposed by dom-testing-library (not the one that would be wrapped by react-testing-library), so we have two options:
1. Write wrapping code for every `findBy*` query that exists today and keep that updated in the future if new queries are ever added. This would include wrapping `within`/`getQueriesForElement` so the `findBy*` queries from those are are wrapped. In addition to wrapping all the `wait*` utilities.
2. Allow configuration of the dom-testing-library `wait*` APIs as this PR does
I don't …
> feat: add asyncWrapper config

- README.md
- typings/queries.d.ts
**What**:
- Remove `| Error` from findBy* return typings.
**Why**:
- The findBy* functions throw errors, so an Error will never actually be returned. Similar to the getBy* functions.
- See https://github.com/kentcdodds/dom-testing-library/issues/226#issuecomment-482396530 for more context.
**How**:
- I updated each of the 4 return typings for the findBy* functions and removed `| Error`.
**Checklist**:
> findBy* typings: Remove Error as a possible return value

- typings/get-queries-for-element.d.ts
**What**:
Fix typings of getQueriesForElement function
**Why**:
There are currently two problems:
1. Type of `queriesToBind` parameter is `BoundFunctions<typeof queries> | BoundFunctions<typeof queries>[]` which is IMO incorrect because the function is doing the binding and thus should receive unbound queries.
1. Type parameter of `BoundFunctions` is hardcoded to `typeof queries` which prevents binding of custom queries
**How**:
1. Parametrised `getQueriesForElement` to enable binding custom queries
1. Changed type of `queriesToBind` to type parameter
**Checklist**:
> Fix typings of getQueriesForElement

- package.json
- src/events.js
- typings/events.d.ts
**What**:
Exposes a utility to create events that can be thrown by `fireEvent`. This is useful in order to have access to the source event attributes see #257
**Why**:
Some components might rely on event attributes created when the event object is created (i.e. `new Event({...eventAttributes})`).
**How**:
As suggested by @kentcdodds in #257:
```js
import {createEvent} from 'dom-testing-library'
const myEvent = createEvent.click(node, eventAttributes)
fireEvent(node, myEvent)
```
However since the event constructor depends on `window` which itself depends on the node, `createEvent` also requires the node to be passed as an argument (not very elegant I admit).
**Checklist**:
Pre-commit hook threw an error on Typescript definitions but I'm really not sure what's wrong, so I committed with …
> Add createEvent that returns the created Event

- src/__tests__/events.js
- src/events.js
Resolves: #263 
**What**: Fix that ensures that `selectionStart` and `selectionEnd` properties are added to event targets.
**Why**: To fulfill the requirement that any property added to the `target` object when firing an event is actually added to the object
**How**: Re-ordering operations in the fire event function
**Checklist**:
> fix(events): add selection-related properties to target

- typings/events.d.ts
**What**:
Allow Document type to be used in fireEvent
**Why**:
Document is not a subtype of Element nor Window
**Checklist**:
> feat(typings): allow document to be used in fireEvent

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**:
See #271 for more context.
**Why**:
It is valid to allow any element to be the label when using `aria-labelledby`, not just `<label>` elements. The current implementation in dom-testing-library restricts to `label` elements.
**How**:
Removed a filter that restricted to `label` elements.
**Checklist**:
> [fix] Allow any element as valid for aria-labelledby

- src/__node_tests__/index.js
- src/events.js
- src/get-node-text.js
**What**:
This PR builds on top of https://github.com/testing-library/dom-testing-library/commit/c4b4efffb19233e1cca9799544e7ab016b3bd916 and adds support for using the [`JSDOM.fragment`](https://github.com/jsdom/jsdom#fragment) API for server side tests.
**Why**:
I think using the JSDOM.fragment API makes sense for SSR only tests. In theory if there was client side logic you would instead be running these tests in a browser context.
With this fragment API there is no `window`, which caused the existing jsdom test to break.
My current thinking is that for SSR tests you really shouldn't be testing events and what not, instead use a browser test for that. Using the fragment API outputs a sane error if you try to do so, while still supporting the same API for everything else.
**How**:
I've …
> fix: support jsdom detached fragments

- src/events.js
**What**:
Fix defaults for various events following
**Why**:
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event
- https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
- https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event
- https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event
**How**:
Using https://developer.mozilla.org/en-US/docs/Web/Events
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs)~
- ~[ ] Typescript definitions updated~
> fix: various event defaults

- typings/query-helpers.d.ts
**What**:
Add types for `buildQueries`
**Why**:
Currently missing
**How**:
Using TypeScript 3.0 support for tuples in rest parameters
**Checklist**:
We should consider using the introduced helper types throughout the definitions just like `buildQueries` is used internally for the bundled queries.
> feat: Add buildQueries types

- src/__tests__/get-node-text.js
**What**:
Currently looks like the `getNodeText` helper is only tested indirectly.
**How**:
I created a new test file for `getNodeText` with the expected behavior.
**Checklist**:
> test: add tests for get-node-text

- typings/pretty-dom.d.ts
**What**:
Add options type of prettyDOM
**Why**:
The [typings file](https://github.com/testing-library/dom-testing-library/blob/master/typings/pretty-dom.d.ts) associated to the `prettyDOM` functions is outdated and misses the `options` type.
**How**:
- Import the `Options` type from [pretty-format](https://github.com/facebook/jest/blob/master/packages/pretty-format/src/types.ts)
- Add the missing `options` type in [pretty-dom.d.ts](https://github.com/testing-library/dom-testing-library/blob/master/typings/pretty-dom.d.ts)
**Checklist**:
I initially opened an issue for the missing documentation on the testing library docs repo: https://github.com/testing-library/testing-library-docs/issues/178
Let me know if I need to update …
> Add options type of prettyDOM

- src/helpers.js
This is a fix for this issue - https://github.com/testing-library/dom-testing-library/issues/315.
**Checklist**:
> fix: Fix setImmediate issue when using with Cypress.

- src/__tests__/__snapshots__/role-helpers.js.snap
- src/__tests__/role-helpers.js
- src/role-helpers.js
**What**:
This PR tries to close #313 😇 
**Why**:
`getByRole('link')` wasn't returning valid anchor elements (read: anchors with `href` attribute).
**How**:
I simply check if `value` is set, and change the return format accordingly. I kept it simple and readable, feel free to suggest some JavaScript calisthenics to improve the resulting function!
**Checklist**:
I discovered that only `<a>` and `<area>` suffer from "value-less" attributes. Following is an output of elements provided by `aria-query` and their associated attribute array:
Thanks! 👋
> Fix getByRole('link') not returning anchor elements

- src/__tests__/element-queries.js
- src/__tests__/pretty-dom.js
- src/__tests__/role.js
- src/queries/role.js
- src/role-helpers.js
**What**:
log available roles when a roles query fails
**Why**:
Closes #286
**How**:
Make a `prettyRoles` export and use that in the missing error message
**Checklist**:
> feat: log available roles when a roles query fails

- src/__tests__/element-queries.js
- src/__tests__/role.js
- src/queries/role.js
**What**:
Added an error message when there are no available roles.
**Why**:
Solves #328.
When unable to locate a role, an error message prints listing the available roles. When there are no available roles, the same message would print without a list of roles. This behavior is confusing/misleading to users.
**How**:
When the length of the string returned by `prettyRoles` is 0, we know there are no roles to be listed. The error message then changes based on that condition.
**Checklist**:
> fix: getByRole error message, when there are no available roles

- .github/ISSUE_TEMPLATE/Bug_Report.md
- .github/ISSUE_TEMPLATE/Question.md
I also removed the `react` version request from the template.
> Fix outdated links on templates

- src/__tests__/pretty-dom.js
- src/__tests__/role-helpers.js
- src/pretty-dom.js
- src/query-helpers.js
- src/role-helpers.js
- typings/query-helpers.d.ts
**What**: add `logDOM` export
**Why**: I was working on #314, but I misunderstood it and changed gears. But I liked the refactor I was working on it.
**How**: Moved some logic around and now pretty-dom is responsible for determining default values for limit and options. I think it's a bit cleaner this way.
This is a breaking change because it basically moves `debugDOM` logic to `prettyDOM`. `debugDOM` was pretty useless after this change, so it's been removed.
It also adds an export for a new `logDOM` which does what it says.
**Checklist**:
> feat(logDOM): add logDOM export

- src/config.js
- src/wait-for-dom-change.js
- src/wait-for-element-to-be-removed.js
- src/wait-for-element.js
- src/wait.js
**What**:
Add a new config value called `asyncUtilTimeout` to allow users to adjust the default timeout for the async utils. 
**Why**:
There doesn't seem to be a nice way to change all of the async utils to use something other than `4500` timeout by default. This is useful for those who have changed the default jest timeout that the `4500` value was intended to be used with.
**Checklist**:
> Add asyncUtilTimeout to config to allow custom default async timeout

- README.md
Can't believe I forgot these ones :)
> dom-testing-library -> DOM Testing Library

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**:
Fixes this bug: https://github.com/testing-library/dom-testing-library/issues/343#issue-484097775
**Checklist**:
> Support textareas with children.

- package.json
- src/__tests__/wait-for-dom-change.js
- src/__tests__/wait-for-element-to-be-removed.js
- src/__tests__/wait-for-element.js
- src/helpers.js
- src/wait-for-dom-change.js
- src/wait-for-element-to-be-removed.js
- src/wait-for-element.js
Related to https://github.com/TheBrainFamily/wait-for-expect/pull/20
> Upgrade wait-for-expect package

- src/__tests__/events.js
- src/events.js
**What**:
Adds specific error message text when `element` / `node` / `event` params are missing for `fireEvent()`
**Why**:
In some cases you may be calling `fireEvent` without giving it an element, e.g.
while it is discouraged, in some cases it is necessary to use `querySelector` or similar or you might be accessing a `results[0]` in an empty array returned by `queryAllBy*`.
When you do that - `fireEvent()` will throw the good old `Cannot convert undefined or null to object`, which means you need to go and look for what exactly happened.
Providing a human readable, specific error message makes it easier to debug such failures.
**How**:
Throw a specific error after testing a condition.
**Checklist**:
> Provide humane error messages for missing fireEvent() params

- .github/PULL_REQUEST_TEMPLATE.md
Types are as of #337 located in the DT repo. PRs have to be prepared and filed once the change in question is released.
> docs(contributing): Update checklist concerning types

- src/__tests__/element-queries.js
- src/__tests__/role.js
- src/queries/role.js
- src/role-helpers.js
BREAKING
Certain<sup>1</sup> elements will no longer be included in `byRole` queries.
Examples:
* `<ul hidden />` will no longer by included in `*byRole('list')`
* `<main aria-hidden="true"><ul /><main>` will no longer return an element in `*byRole('list')` or `getByRole('main')`
**What**:
Implement https://www.w3.org/TR/core-aam-1.1/#exclude_elements2 with the following deviation:
* `role="none"` and `role="presentation"` is included (not following `MUST` criteria)
I feel like this is more of a concern for an actual a11y tree implementation. `getByRole('presentation')` not returning anything even if the element is visible is probably confusing but I could see us throwing an error here. We could argue that one should use `getByTestId` instead since this makes it obvious you're not …
> feat(byRole): Exclude inaccessible elements

- src/queries/label-text.js
**What**:
* Don't use [`NodeList.prototype.forEach()
`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility)
**Why**:
* Crashes in IE 11 when using `byRoles`
**How**:
* Wrap in `Array.from`
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs)~
- ~[ ] I've prepared a PR for types targetting https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom~
- ~[ ] Tests~ Would require running tests in browsers. Since tests are still passing then it doesn't matter how it's implemented.
> fix: byLabel crashing in IE 11

- src/__tests__/events.js
- src/events.js
Hi all!
This is my first PR to a popular OSS project.
**What**:
Forms have ```submit```, but lack ```reset``` event.
**Why**:
Using form events instead of direct button callbacks comes handy sometimes, when using form templates with variable content.
**How**:
Events were extended to contain ```reset``` event applicable on ```<form />``` tags.
**Checklist**:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom
**Comments**:
1. I think updating docs is not necessary since the following line covers everything.
```
Convenience methods for firing DOM events. Check out src/events.js for a full list as well as default eventProperties.
```
2. I can prepare a types PR if this one will be accepted.
> feat(events): add form reset event

- src/__tests__/element-queries.js
- src/role-helpers.js
IE11 returns `undefined` for missing `parentElement`.
fix: In IE11 when an element lacks `parentElement` it returns `undefined` instead of `null`.
**Why**: Because otherwise you get these errors
```
TypeError: Unable to get property 'hidden' of undefined or null reference
error properties: Object({ number: -2146823281 })
at <Jasmine>
at shouldExcludeFromA11yTree (eval code:824:5)
at Anonymous function (eval code:995:5)
at Anonymous function (eval code:28:7)
at filter (eval code:11:5)
at queryAllByRole (eval code:994:3)
```
**Checklist**:
- [x ] Ready to be merged
> fix: shouldExcludeFromA11yTree runs in IE11

- src/__tests__/pretty-dom.js
- src/pretty-dom.js
Hey,
I face an issue and come with this pr :)
**What**:
Add strict check for `dom`'s `outerHTML` field
**Why**:
To improve DX. 
As a new user I've called `debug(x)` where `x` was a result of `queryAll*`. I've missed that `queryAll*` returns an array and got `TypeError: Cannot read property 'length' of undefined` in my terminal.
**Checklist**:
> Add strict check for `dom` type

- package.json
- src/role-helpers.js
**What**: Upgrade all deps, but most notably `wait-for-expect` which always uses real timers
**Why**: Related: #342 
**How**: `yarn upgrade-interactive --latest'
**Checklist**:
> feat: update wait-for-expect which always uses real timers

- src/__node_tests__/index.js
- src/role-helpers.js
**What**:
Get window from passed element
**Why**:
element might be passed from another window/frame
**How**:
Use `element.ownerDocument.defaultView`. This is safe to evaluate since we expect an `Element`. `ownerDocument` is only `null` for `Document` (https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument)
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs)~
- ~[ ] I've prepared a PR for types targetting ~https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom
> fix(byRole): Don't assume window context

- src/__tests__/role-helpers.js
- src/index.js
- src/queries/role.js
- src/role-helpers.js
Looking for better names of this function.
**What**:
* Export helper method that is used in `byRoles` queries to exclude inaccessible elements
**Why**:
* To implement a custom test matcher like `expect(element).toBeInaccessible()`
This is useful if you want to test relationships between elements which are established via `aria-controls`. We want to test that the value of `aria-controls` is valid by checking that `expect(document.getElementById(control.getAttribute('aria-controls'))).toBeInTheDocument()` but we want to make sure that at that point the element is still excluded from the a11y tree.
Another use case might be if you queried the element with something other than `byRole` and you want to make sure the element is (in)accessible.
**How**:
* "just" export it
**Checklist**:
[docs …
> feat: Export isInaccessible

- src/queries/role.js
**What**:
Addresses #379
**Why**:
Queries can be used when polling the DOM. If the query is slower than the polling rate we'll run into timeouts
**How**:
Since |elements| >> |elements with role| and getting the role is far less expensive than deciding if an element is part of the a11y tree it's far cheaper to query the elements for the role before checking if an element is part of the a11y tree.
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs)~
> feat(byRole): Improve performance

- src/role-helpers.js
**What**: fix coverage
**Why**: I merged https://github.com/testing-library/dom-testing-library/pull/381 without realizing that it didn't have 100% coverage. Now it wont be released. Unless I'm mistaken, we don't need to have coverage on that else branch because it's temporary code anyway.
**How**: add istabul ignore comment
**Checklist**:
> test: fix coverage

- src/__tests__/element-queries.js
**What**:
Fixes a lint error.
**Why**:
Running `npm run validate` after pulling a fresh copy of the repo resulted in this error:
```
[lint] .../dom-testing-library/src/__tests__/element-queries.js
[lint]   372:3  error  Move all hooks before test cases  jest/prefer-hooks-on-top
```
It appears that it was triggered by [this commit](https://github.com/kentcdodds/eslint-config-kentcdodds/commit/0298d2e2d83868df2342afac0dcda4498a3c7de9#diff-b05a92a4bf52283f912cfbf2de67b458) in `eslint-config-kentcdodds`.
**How**:
Moves an `afterEach` call to the top of its enclosing block.
**Checklist**:
- [x ] Ready to be …
> Fix lint error from jest/prefer-hooks-on-top

- src/__tests__/events.js
**What**:
Add tests to check event propagation.
**Why**:
To have a better coverage. Currently, only firing events on elements directly is being tested.
**How**:
1. Create a `div` (being the most generic element)
1. Add an event listener
1. Create an inner `div`
1. Wrap an inner `div` inside of a `div`
1. Fire an event on inner `div`
1. Expect the event listener on the outer `div` to fire
**Checklist**:
I also fixed what I believe to be copy-paste error with the `message` event.
> test: add bubbling tests

- .codesandbox/ci.json
- src/index.js
Please don't merge this yet
Testing:
Edit: It doesn't at the moment so we use https://github.com/kentcdodds/dom-testing-library-with-anything
> chore: Add codesandbox ci config

- src/helpers.js
**What**:
Added a check to make sure globalObj.setTimeout exists before referencing the _isMockFunction parameter.
**Why**:
I was getting the following error in my console when using ```@testing-library/react``` in my project.
```TypeError: Cannot read property '_isMockFunction' of undefined```
**How**:
Made sure ```globalObj.setTimeout``` existed before referencing the child property ```_isMockFunction```
**Checklist**:
[DefinitelyTyped] (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) N/A
> fix: make sure setTimeout exists on global

- src/pretty-dom.js
refs #413 
refs #161 
**What**:
Not all environments (particularly the browser, where testing via tools like Karma occurs) have access to the `process` variable. There is already checking to ensure that its member properties have fallbacks, and this ensures that if it is simply unavailable the same fallback occurs.
**Why**:
I'd like to begin the work of supporting Karma and web components.
**How**:
Extra test for `process`.
**Checklist**:
> fix(pretty-dom): Ensure safe process.env access

- src/__tests__/element-queries.js
- src/__tests__/queries.find.js
- src/queries/role.js
**What**: Adding support for `*ByRole` query to query multiple roles.
**Why**:
> The *ByRole query should support querying elements that have multiple role values defined. the ARIA spec defines the role attribute as a whitespace delimited list of values, of which the engine will choose the first supported value. See w3.org/TR/wai-aria-1.2/#introroles. Querying by role when testing should take this into account and find roles matching any of the items in the list rather than only the entire role attribute.
Closes: #411 
**How**: With the help of a flag named `queryFallbacks`, `*ByRole` queries can query multiple roles. If the flag is missing and you're trying to query a role that is located on the right side, then this will throw an error. The working is same as mentioned in …
> feat(ByRole): Add support for fallback roles

- src/__tests__/events.js
- src/events.js
Added popstate to events map with respective tests #427
**What**:
popstate history event is not supported.
**Why**:
Adding this event will allow the testing of custom router implementations
**How**:
Added new popstate event applicable on window.
**Checklist**:
> feat(event): add new history popstate event

- src/__tests__/screen.js
- src/get-queries-for-element.js
- src/screen.js
**What**:
A debug method is being added to the screen object.
**Why**:
Facilitate debugging tests without having to always modify imports.
**How**:
Added the debug method to the screen object, following the pattern for the debug method from render in react-testing-library.
**Checklist**:
**Would close**
https://github.com/testing-library/dom-testing-library/issues/417
**Docs PR**: 
https://github.com/testing-library/testing-library-docs/pull/362
> Add a debug method to screen.

- src/__tests__/element-queries.js
Remove the work test in the description
**What**:
Remove the word `test` from test description `test the debug helper prints the dom state here` in element-queries fixes #436
https://github.com/testing-library/dom-testing-library/blob/3805b2772f93d2e5a16858d50231eeafb6c6e484/src/__tests__/element-queries.js#L680
**Why**:
Running `npm run lint` returns a  jest/valid-title warning
**How**:
**Checklist**:
No change to code and functionality and running `npm run test` -> `a` returns all test passing
> fix(element-queries)  jest/valid-title warning in test

- src/__tests__/element-queries.js
- src/__tests__/get-by-errors.js
- src/queries/display-value.js
**What**:
- Improve warning message in ByDisplayValue queries: "with the value:" -> "with the display value:" 
- Update snapshots for **element not found** error message.
- Ensure that **multiple elements** error message is changed as expected (No test failed when message was changed).
**Why**:
As said in #442, the current message is quite misleading.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) (N/A)
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) (N/A)
> fix(ByDisplayValue): improve warning message

- src/events.js
Fixes #421
**What**:
Use `createEvent` instead of `new Event` if `Event` is not constructable
**Why**:
`new Event` is not supported in IE 11
**How**:
Use https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
**Checklist**:
- ~[ ] I've prepared a PR for types targeting~
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom)~
> fix: fireEvent in IE11

- package.json
- src/__tests__/__snapshots__/wait-for-dom-change.js.snap
- src/__tests__/wait-for-dom-change.js
- tests/setup-env.js
Not sure which version we should use. While the latest is 16 it isn't the default version used in jest. Ideally we would test with jsdom 15 and 16 just to be aware of changes between those versions.
**What**:
Bump used jsdom version to 15.2.1
**Why**:
jsdom 15 has MutationObserver support as well as perf improvements. 
**How**:
- fixing breaking changes in jest and jsodm
**Checklist**:
> chore: Bump jsdom to 15

- src/__tests__/__snapshots__/get-by-errors.js.snap
- src/__tests__/get-by-errors.js
- src/config.js
- src/queries/label-text.js
- src/query-helpers.js
Closes #360
**What**:
Adding a showLogOnFail option to configure logging for getBy* and getAllBy* when the query fails. 
**Why**:
Logging the entire document when working with larger components can obscure other error messages. I often find these explicit error messages are more helpful than scrolling through the output from prettyDom. If the DOM needs to be examined then debug() can be used. @benmonro also mentions that this makes working with Testcafe harder.
**How**:
`getElementError` looks at the config and determines what to output as an error:
```javascript
function getElementError(message, container) {
const errorMessages = getConfig().showLogOnFail
? [message, prettyDOM(container)]
: [message]
return new Error(errorMessages.filter(Boolean).join('\n\n'))
}
```
**Checklist**:
[docs …
> feat(config): add customGetElementError config option

- package.json
- src/__tests__/__snapshots__/role-helpers.js.snap
- src/__tests__/role.js
- src/queries/role.js
- src/role-helpers.js
**What**:
Add a `name` option to `ByRole` queries. If a `name` is provided then the error messages will include the accessible name of each element with a role.
**Why**:
Better alternative to `byText` (especially for buttons) or `byLabelText` when `aria-label` or `aria-labelledby` is used (e.g. for custom Select implementations) or `byTestId` for "semantic" elements e.g. menuitem. 
There's a bit more to write in https://testing-library.com/docs/guide-which-query to explain why you still might want to use byLabelText('street') instead of `byRole('textbox', { name: 'street' })`.
**How**:
Using https://github.com/eps1lon/dom-accessibility-api#readme which implements https://www.w3.org/TR/accname-1.2/ and is tested against web-platform-tests
**Checklist**:
[docs …
> feat(byRole): Add `name` filter

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**:
Updating the ByLabel queries to work with `<select>` components. It didn't work properly with `<select>` components because the text from the options is part of the label's `textContent` property.
**Why**:
It seems super counter-intuitive that it works really well for other inputs (even `<textarea>`), but not for `<select>`. I think having this working properly will make this library an even greater joy to use :heart:
**How**:
I used the same strategy used for `<textarea>` components, but instead removing the `textContent` value from the `<select>` components from the label's `textContent`. 
**Checklist**:
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom …
> Fixed ByLabel queries to work with selects

- package.json
- src/__tests__/fake-timers.js
- src/__tests__/pretty-dom.js
- src/__tests__/role-helpers.js
- src/__tests__/screen.js
- src/__tests__/wait-for-dom-change.js
- src/__tests__/wait-for-element-to-be-removed.js
- src/__tests__/wait-for-element.js
- src/__tests__/wait.js
- src/config.js
- src/pretty-dom.js
- src/role-helpers.js
- src/wait-for-dom-change.js
- src/wait-for-element-to-be-removed.js
- src/wait-for-element.js
- src/wait.js
- tests/setup-env.js
**What**: Make `wait` use a MutationObserver in addition to the previous behavior
**Why**: This way we can get rid of `waitForDomChange` (in a future release) *and* we drastically simplify the other async utilities. `wait` also gets a super-power of being able to re-run the callback faster than the interval when the DOM is changed, so this should speed up people's tests who are using `wait` today. Closes #376
**How**: Remove `wait-for-expect` (cc @lgandecki) because it wont work nicely with this approach. I also refactored the other utilities to build on top of `wait` (which is something I've wanted to do for a long time now).
**Checklist**:
> feat(wait): wait will now also run your callback on DOM changes

- package.json
- src/__tests__/helpers.js
- src/events.js
- src/helpers.js
- src/wait-for-dom-change.js
- src/wait.js
**What**: Remove `@sheerun/mutationobserver-shim` from the project
**Why**: MutationObserve is supported by all major platforms we're targeting, and people can still add the shim themselves if they need to.
**How**: Now, we simply retrieve the `window` from the node they give us, and then reference the MutationObserver off of that.
**Checklist**:
Closes #413
> feat: remove mutationobserver shim

- src/__tests__/wait-for-element-to-be-removed.js
- src/wait-for-element-to-be-removed.js
**What**: feat(waitForElementToBeRemoved): support passing an element directly
**Why**: Makes using this async utility simpler
**How**: Overload the argument for this so the callback can be a DOM node (or array of DOM nodes). In that case, we capture those and reassign the callback to a function that checks whether those are still contained in their original parent element
**Checklist**:
Really excited about this one.
> feat(waitForElementToBeRemoved): support passing an element directly

- src/__tests__/wait.js
- src/wait.js
**What**: Removes the default no-op callback from `wait`
**Why**: That encourages relying on the implementation detail of waiting for the "next tick" and explicit expectations should be used instead.
**How**: Removed the default and added a test to check for the rejected response
**Checklist**:
BREAKING CHANGE: If you used `wait()` in the past, you now have to supply a callback. Relying on the "next tick" is an implementation detail and should be avoided in favor of explicit expectations within your wait callback.
> feat(wait): remove default no-op callback

- src/queries/label-text.js
**What**:
fixes crash in Edge when using `getAllByLabelText`
**Why**:
forEach is not implemented in NodeList in edge 15
**How**:
Convert NodeList to array before using forEach
**Checklist**:
- ~[ ]~ I've prepared a PR for types targeting
> fix(allByLabelText): forEach on NodeList is not supported in edge

- src/role-helpers.js
**What**:
Fixes crash when logging roles in older browsers (namely IE11)
**Why**:
Objec.entries is not implemented in older browsers
**How**:
Use Object.keys
**Checklist**:
- ~[ ]~ I've prepared a PR for types targeting
> fix(prettyRoles): crash in older browsers

- .travis.yml
- package.json
This is a follow-up to #459.
**What**: support older Node 10 versions
**Why**: to make the upgrade easier since there doesn't appear to be a hard requirement to use Node 10.18 (see https://github.com/testing-library/dom-testing-library/pull/459#issuecomment-595565564).
**How**: changed `engines.node` from `>=10.18` to `>=10`.
**Checklist**:
> fix: support Node >=10

- .travis.yml
**What**: Ensure we actually run builds against the lowest version of Node that we support
**Why**: Node 10.0.0 is our lowest version of support
**How**: Be specific about the version of Node in `travis.yml` - specifying just `10` pulls down the latest Node 10
**Checklist**:
> Run Travis builds on Node 10.0.0

- src/query-helpers.js
**What**: Using the `wait` method instead of `waitForElement` for the `findBy` queries
**Why**: To prevent that deprecations are logged
Closes #468
**How**: Replace `waitForElement` with `wait` (and by renaming `waitForElementOptions` to `waitOptions`)
**Checklist**:
Something else that I've encountered, is that the changes made in #461 didn't make it into the [beta branch](https://github.com/testing-library/dom-testing-library/blob/beta/src/wait.js#L12).
> fix: use wait in findBy queries

- src/index.js
BREAKING CHANGE: Use `getQueriesForElement` or `within` instead.
**What**: Remove `bindElementToQueries` in favour of `getQueriesForElement` and `within`.
**Why**: https://github.com/testing-library/dom-testing-library/issues/471#issuecomment-596159437
**How**: Remove `bindElementToQueries` export
**Checklist**:
> feat: remove `bindElementToQueries`

- src/query-helpers.js
**What**: fix(find*): waitForElement was still in use 
**Why**: That method has been deprecated and should not be used (was showing a warning to people using `find*`
**How**: find/replace basically
**Checklist**:
> fix(find*): waitForElement was still in use

- src/__tests__/wait-for-dom-change.js
- src/wait-for-dom-change.js
**What**:
If you are migrating from `waitForDomChanges`, it suggests using `wait` instead, which is also deprecated and it suggests `waitFor`. The link in this particular warning is linked to `waitFor`.
```
`waitForElement` has been deprecated. Use a `find*` query ...
```
```
`waitForDomChange` has been deprecated. Use `wait` instead ...
```
but then it says `wait` is also deprecated:
```
`wait` has been deprecated and replaced by `waitFor` instead. In most cases you should be able to find/replace `wait` with `waitFor`.
```
**Why**:
☝️ 
**How**:
Updated deprecation warning string with the correct suggestion
**Checklist**:
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-librar …
> docs: corrects deprecation warning for waitForDomChange

- src/__tests__/wait-for-element-to-be-removed.js
- src/__tests__/wait-for.js
- src/wait-for-element-to-be-removed.js
- src/wait-for.js
**What**: feat(waitFor*): improve stacktrace for timeout errors
**Why**: Closes #491
Way improved:
Before: 
```
● can create a list item for the book
Timed out in waitForElementToBeRemoved.
at node_modules/@testing-library/dom/dist/wait-for-element-to-be-removed.js:51:13
at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:50:22)
```
After:
```
● can create a list item for the book
Timed out in waitForElementToBeRemoved.
34 | 
35 |   const div = document.createElement('div')
> 36 |   await waitForElementToBeRemoved(() => div)
|         ^
37 | 
38 |   await waitForElementToBeRemoved(() =>
39 |     utils.getByRole('heading', {name: 'Loading...'}),
at waitForElementToBeRemoved (node_modules/@testing-library/dom/dist/wait-for-element-to-be-removed.js:22:24)
at renderBookScreen …
```
> feat(waitFor*): improve stacktrace for timeout errors

- package.json
**What**:
Fixes outdated types being used
**Why**:
Types are outdated
**How**:
Bump `@types/testing-library__dom`
**Checklist**:
- ~[ ]~ I've prepared a PR for types targeting
- ~[ ]~ Tests
> fix: Bump types

- src/__tests__/query-helper.js
- src/query-helpers.js
**What**:
If you try to call getElementError in a custom query according to the documentation, you will get an error.
**Why**:
getElementError was removed in #452.
**How**:
redefine to queryHelpers
**Checklist**:
NOTE: 
I asked a question about this issue. #508 
This can be done by require of `@testing-library/dom/dist/config`, but I'm wondering if that's the official way to do it (It was a question I wanted to ask on that `issue` ).
Please close this PR if that is official way.
Thanks!
> fix: queryHelpers.getElementError is not a function

- src/__tests__/wait-for.js
- src/wait-for.js
**What**:
Closes #509
**Why**:
To improve error message and error stack trace
**How**:
Checking if `callback` is a function.
**Checklist**:
> feat(waitFor): improve error message for non-function callbacks

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**:
Bug-Fix: Changes the *ByLabelText queries so that, when finding form controls that are children of labels, only the first form control is returned.
**Why**:
Following up on the discussion in #373 that started with [this comment](https://github.com/testing-library/dom-testing-library/pull/373#issuecomment-609843685)
**How**:
When finding children of labels, I filtered the children down to only those that matched the selector and grabbed the first one.
**Checklist**:
> fix: Only return first child element in label query

- .travis.yml
- package.json
> test(ci): use latest 10 LTS release

- src/__tests__/wait-for-element.js
- src/wait-for-element.js
**What**:
Same issue as https://github.com/testing-library/dom-testing-library/pull/478 but in the `waitForElement` deprecation warning. The warning when you use `waitForElement` currently says to use either `find*` or `wait` instead, but `wait` is deprecated as well.
**Why**:
Up-to-date deprecation warnings
**How**:
Updated warning to say `waitFor` instead of `wait`
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) **N/A**
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) **N/A**
> fix: update deprecation warning for waitForElement

- src/__tests__/wait-for.js
- src/config.js
- src/wait-for.js
**What**:
Improve error stack traces for async errors
**Why**:
Improve error stack traces for async errors
**How**:
-changed the on timeout function  
**Checklist**:
i have made changes suggested by KCD , please let me know if i need to do any more changes will be happy to do ... this is my first PR to Open source
> Improve error stack traces for async errors

- package.json
- src/__tests__/role-helpers.js
**What**: update everything
**Why**: To stay updated
**How**: `npx ncu -u`
This also allowed us to fix a test that was busted due to jsdom support being old. kcd-scripts uses the latest jest which uses the latest jsdom. Wahoo!
**Checklist**:
> chore: update all the things

- src/__tests__/role.js
- src/queries/role.js
To better understand, review commits individually. The first commit describes the current behavior and the second commit applies the expected behavior.
**What**:
- Closes #549
- Exclude `container` when displaying the available roles for a bound `ByRole`
**Why**:
- The `container` was never part of the considered elements due to how `.querySelectorAll` works.
**How**:
Start with `container.children`
**Checklist**:
- ~[ ] I've prepared a PR for types targeting
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom)~
>  fix: Exclude container in the list of queryable roles

- src/__tests__/events.js
- src/events.js
**What**:
Resolves #551
Adds a convenience option to approximate the `dataTransfer` event property when firing events
**Why**:
Provides a consistent and convenient way to populate `dataTransfer` properties, much like populating `target` properties. This would help developers better simulate testing for drag and drop interactions.
There was previous discussion and feature validation over in https://github.com/testing-library/react-testing-library/issues/339
**How**:
Update the `fireEvent.*` functions to populate the `dataTransfer` property for events only when defined in the `eventProperties` (second argument).
The property is assigned to the event object in a simple way. It does not construct the `DataTransfer` object and for good reasons. `DataTransfer` is  privately handled and …
> feat(events): Add dataTransfer event property option

- types/get-queries-for-element.d.ts
- types/queries.d.ts
- types/wait-for-dom-change.d.ts
- types/wait-for-element-to-be-removed.d.ts
- types/wait-for-element.d.ts
**What**: Fixing invalid imports
```
> tsc -p tsconfig.all.json
node_modules/@testing-library/dom/types/queries.d.ts:3:32 - error TS2307: Cannot find module 'wait-for'.
3 import { waitForOptions } from 'wait-for';
~~~~~~~~~~
node_modules/@testing-library/dom/types/wait-for-dom-change.d.ts:1:32 - error TS2307: Cannot find module 'index'.
1 import { waitForOptions } from "index";
~~~~~~~
node_modules/@testing-library/dom/types/wait-for-element-to-be-removed.d.ts:1:32 - error 
TS2307: Cannot find module 'wait-for'.
1 import { waitForOptions } from "wait-for";
~~~~~~~~~~
node_modules/@testing-library/dom/types/wait-for-element.d.ts:1:32 - error TS2307: Cannot find module 'wait-for'.
1 import { waitForOptions } from "wait-for";
~~~~~~~~~~
Found 4 errors.
```
**Why**: It's breaking my builds …
> Fix incorrect imports in types

- src/__tests__/role.js
- src/role-helpers.js
**What**:
Consider explicit roles first when pretty printing roles.
**Why**:
`getRoles` printed a different role than what `queryAllByRole` could query. Closes #553
**How**:
Check for existence of `role` attribute first and use the first role from that list. I haven't put much thought into fallback roles but we can discuss it when it becomes an issue.
Technically this isn't correct. html-aria disallows (some) roles for certain HTML elements. But we didn't consider this for `queryAllByRole` either and it isn't clear if we should restrict it (e.g. chrome's a11y pane does not).
**Checklist**:
- ~[ ] I've prepared a PR for types targeting …
> fix: Consider explicit role when pretty printing roles

- package.json
**What**: Downgrade `pretty-format` to v25.
**Why**: The newer v26 bumps the minimum required version of Node. See #563.
**How**: Update version in package.json
**Checklist**:
> chore: revert pretty-format dependency upgrade

- types/screen.d.ts
**What**: Typings of `screen.debug` helper does not reflect `prettyDOM` signature
**Why**: Prevent this kind of error when calling `screen.debug()` without params from a typescript file: 
```
node_modules/@testing-library/dom/types/screen.d.ts:11:9
11         element: Element | HTMLDocument | Array<Element | HTMLDocument>,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An argument for 'element' was not provided.
```
**How**: Updated typings
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) N/A but the doc already mention that we can use `screen.debug()`
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) <- Is this still maintained since it was migrated to this repo?
> fix(TS): declare first parameter of screen.debug as optional

- types/__tests__/type-tests.ts
- types/query-helpers.d.ts
> fix(types): add fourth param to build findAllBy and findBy queries

- types/queries.d.ts
**What**:
The TypeScript documentation for `ByRoleOptions.queryFallback` has a typo.
**Why** / **How**:
Fixed the typo.
**Checklist**:
> docs: Fix progressbar typo for queryFallbacks

- package.json
- types/__tests__/type-tests.ts
- types/tsconfig.json
- types/wait-for.d.ts
**What**: 
Change typescript definitions to forbid async functions in `waitFor`.
**Why**: 
Promises returned by `waitFor` do not work as one might expect (i.e. a rejected promise does not mean the same thing as a throw in the function). So these examples work differently:
```
await waitFor(() => throw new Error());
await waitFor(async () => throw new Error());
```
So in order to prevent a user from using an async function, a typescript error would be good. This is what this PR adds.
**How**:
I've added a conditional type to the return value of waitFor's callback that makes it impossible to return a promise from the callback.
**Checklist**:
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/ty …
> fix(TS): Forbid async function as callback argument for waitFor

- src/__tests__/wait-for-element.js
- src/wait-for-element.js
Fixes https://github.com/testing-library/react-testing-library/issues/677
> Fix misleading advice in waitForElement deprecation warning

- src/__tests__/suggestions.js
- src/config.js
- src/queries/text.js
- src/query-helpers.js
- src/suggestions.js
**What**: properly handles `ignore` option in suggestions.
**Why**: previously if you try to get a suggestion on a random element it would not ignore script, style tags and suggest getByText on those elements.
**How**: `.matches("script, style")`
**Checklist**:
> fix: handle ignores for ByText in suggestions

- src/__tests__/suggestions.js
- src/suggestions.js
**What**: 
* Fixed bug that would suggest a query that would yield a different element than the one being verified.  Also added additional test for label > title.
* Fixed bug that would suggest get by role w/ name that had un-escaped regexp that would not yield the element intended.
**Why**: suggestions should give the same results, just using better queries.
**How**: 
* use specific || implied roles.
* escape regexp
**Checklist**:
> fix: more improvements to suggestions

- types/config.d.ts
**What**: We forgot to add the `throwSuggestions` option in the global config
**Why**: To have intellisense. In TS projects we also currently get an error while trying to do the following.
```ts
configure({ throwSuggestions: true });
```
**How**:
**Checklist**:
Should we try to keep the naming consistent? 
For the global config it's `throwSuggestions` , while the config on a query basis is `suggest`.
```
configure({throwSuggestions: true})
// vs
screen.getByText('Increment', {suggest: true})
```
> fix: update config type

- src/__tests__/event-wrapper.js
- src/config.js
- src/events.js
- types/config.d.ts
**What**: feat(config): add new `eventWrapper` config for wrapping fireEvent
**Why**: So we don't have to do this nonsense: https://github.com/testing-library/react-testing-library/blob/0afcbea3c3d1ddce218a36d963d39fa83f9a7cf6/src/pure.js#L107-L128
**How**: Add the config
**Checklist**:
This is intended for supporting `act` in React, but should be useful for
other frameworks (I think it could help with triggering change detection
for angular for example).
Ref: https://github.com/testing-library/user-event/issues/188,
https://github.com/testing-library/user-event/issues/255, …
> feat(config): add new `eventWrapper` config for wrapping fireEvent

- package.json
**What**:
Closes #591
**Why**:
Use implemented behavior of browsers over spec 
**How**:
Bump `dom-accessibility-api`
**Checklist**:
- ~[ ] I've prepared a PR for types targeting
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom)~
> fix: Bump dom-accessibility-api

- src/__tests__/suggestions.js
- src/suggestions.js
**What**:
I've added more data to the object that `getSuggestedQuery` returns. Before this change, the returned value would be something like:
```js
{
queryName: 'Role',
}
```
By calling the `toString` method, the caller would get more information, but formatted as string: (the full expression statement)
```
getByRole('button', { name: /submit/i })
```
With this change, the caller gets rich data, upon which he can build tooling.
Example result:
```js
{
queryName: 'Role',
queryMethod: 'getByRole',
queryArgs: ['button', { name: /submit/i }],
variant: 'get'
}
```
Before this change, queries were returned with double quotes and without spacing. I've updated the `toString()` method to match the style that's being used throughout the docs.
```js
// before
getByRole("button", {name: /submit/i}); …
```
> feat: return more data from getSuggestedQuery to support tooling

- .gitignore
- src/__tests__/suggestions.js
- src/suggestions.js
**What**:
I've adjusted the query suggestions to use regex-based text matchers when possible. This impacts all query methods, except for the `Role` variants. I believe `roles` need to be exact.
Currently, suggestions like these are made:
```js
screen.getByRole('button', { name: /google search/i }) // regex name option
screen.getByText('A privacy reminder from Google')     // string text arg
```
With this PR, the same suggestions look like:
```js
screen.getByRole('button', { name: /google search/i }) // regex name option
screen.getByText(/a privacy reminder from google/i)    // regex text arg
```
**Why**:
Because I believe that tests shouldn't fail due to a change in capitalization.
For that same reason, we already did this for `name` option in `Role` queries:
```js
// current suggestion …
```
> feat: use regex based TextMatch for suggestions

- src/__tests__/suggestions.js
- src/suggestions.js
**What**:
I've added an option to specify the desired method to the `getSuggestedQuery` method.
**Why**:
To enable tools (such as https://testing-playground.com) to show specific suggestions instead of only the most recommended one.
**How**:
`getSuggestedQuery` accepted the arguments `element, variant`, I've extended that to `element, variant, method`.
Method defaults to "best", but if specified, only the requested query will be suggested, or none at all.
This enables us to use it like:
```js
getSuggestedQuery(input, 'get', 'PlaceholderText'));
```
If that call results in a valid suggestion, the suggestion is returned otherwise it will return `undefined`. It will not fall back to alternative methods!
The default behavior of the method has been left unchanged. A call like:
```js …
```
> chore: add option to get specific query suggestions

- src/__tests__/suggestions.js
- src/suggestions.js
**What**:
Following up #627 I have updated `canSuggest` function because it only works when methods where exactly the same.
**Why**:
because I think that  `getSuggestedQuery` should return the same result for method 'Role' and method 'role'.
**How**:
I have compared lowecase strings.
**Checklist**:
> fix: canSuggest should not be case sensitive 

- src/suggestions.js
- types/suggestions.d.ts
**What**:
I have updated typescript definitions
**Why**:
As before you can't pass both variant and method parameters
**How**:
I have added two new types `Variant` and `Method` and used them as types for the respective params.
Method params is also optional
**Checklist**:
> fix: typescript definitions for suggestions

- src/__tests__/wait-for-element-to-be-removed.js
- src/wait-for-element-to-be-removed.js
- types/wait-for-element-to-be-removed.d.ts
**What**: 
A possible fix for issue #610 -> a refinement to the return value (and TS type) for `waitForElementToBeRemoved`
**Why**:
There's a mismatch between implementation and type signature (and docs)
**How**: 
I've updated the return type to `Promise<void>` (and implemented by returning undefined)
For more details, please refer to the commit message(s)!
**Checklist**:
> [#610] waitForElementToBeRemoved: fix return type

- src/__tests__/helpers.js
- src/helpers.js
**What**:
Added a nice explicit error message for the case in #609 of a `Promise` or Promise-like passed to a function that expects a DOM node.
**Why**:
Better error messages = happier users! 💝 
**How**:
Per https://github.com/testing-library/dom-testing-library/issues/609#issuecomment-643660994, checked if `node.then instanceof Function`.
**Checklist**:
I'm not attached to this particular error message, if a reviewer can think of something better that'd be nice.
> Added explicit error message for Promises passed to getWindowFromNode

- src/user-event/__tests__/helpers/utils.js
- src/user-event/__tests__/select-options.js
- src/user-event/select-options.js
Migrated from testing-library/user-event#344 by @ben-dyer
**What**: Prevent a select's value from changing with `selectOptions` if it is disabled
**Why**: It's possible to change the value of a disabled select using `selectOptions`. For instance this is passing:
```
const {
container: {firstChild: select},
} = render(
<select disabled>
<option>No value selected</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
</select>,
)
expect(select.selectedIndex).toBe(0)
userEvent.selectOptions(select, '1')
expect(select.selectedIndex).toBe(1)
```
**How**: Exit early in `selectOptions` if the element is disabled, similar to what is done in `clear` and `upload`
**Checklist**:
> fix(userEvent): don't select option if select is disabled

- src/__tests__/helpers.js
- src/helpers.js
**What**:
This change will fix issue #612.
**Why**:
With the version 26.0.0 of jest the `jest.useFakeTimers` function uses `@sinonjs/fake-timers`.
With this new package the property `_isMockFunction` is no more available.
**How**:
To fix the issue I have added a new check to `clock` property.
`@testing-library/dom` is now compatible with both version of `useFakeTimers`, the legacy and the modern one.
**Checklist**:
> fix: runWithRealTimers to be compatible with new version of jest

- src/__tests__/suggestions.js
- src/suggestions.js
**What**:
Currently `getSuggestedQuery` always uses `data-testid` to find relevant
elements. This change updates it to use the configured `testIdAttribute`
if one has been set in the configuration. (Thanks to @smeijer for 
pointing me in the right direction for a solution.)
**Why**:
If a user has set `testIdAttribute` suggestions will run `getByTestId` against the wrong elements.
**How**:
There's a new test to verify this behavior and a small change to the suggestions code.
**Checklist**:
This does not appear to solve #643 yet, but it's a first step in narrowing down the possible cause.
> Use custom testIdAttribute in getSuggestedQuery

- src/__tests__/helpers.js
- src/helpers.js
**What**:
Modify `runWithRealTimers` so that real timers are only used if they were faked by Jest's legacy or modern implementation of fake timers.
Also, when restoring Jest's fakes, be explicit in specifying whether we're restoring the `modern` or `legacy` fakes.
**Why**:
A recent change to `runWithRealTimers` added a check for the `clock` attribute on `setTimeout` so that we can determine whether timers were faked with Jest's modern fake timers (which are based on `@sinonjs/fake-timers`).  See [issue thread](https://github.com/testing-library/dom-testing-library/issues/612#issuecomment-645491120).
Unfortunately, this attribute can be present when users are not using Jest's fake timers and are using sinonjs.  Also, when `useFakeTimers` are invoked without parameters in Jest 26, the …
> Limit use of realTimers to Jest's fakeTimers

- package.json
- src/__tests__/queries.find.js
**What**:
`<header>` is not recognized as `banner` role, and cannot be selected with `getByRole("banner")`.
See also: #578
**Why**:
It should work correctly according to the [specs](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/banner.html).
**How**:
Update `aria-query` dependency. The latest [aria-query version](https://github.com/A11yance/aria-query/releases/tag/v4.2.2) fixes the issue of failing to recognize `<header>` as a `banner` role.
**Checklist**:
Fixes: #578
> fix: Treat header as banner role

- src/__tests__/helpers.js
- src/helpers.js
**What**:
- Improve suggestion when a Promise is passed to a `fireEvent` method
**Why**:
- A `getBy` query can't be awaited and the messages says `await screen.getBy`
**How**:
- Change the message (and the test)
**Checklist**:
> fix: improve suggested message, can't await getBy

- src/__tests__/element-queries.js
- src/__tests__/suggestions.js
- src/role-helpers.js
- src/suggestions.js
fix #663 
**What**:
I have fixed all the tests that failed
**Why**:
Because after the update of `aria-query` something didn't work
**How**:
I have made two changes in this PR:
1) With the new aria specifications `input` without a role has a `textbox` as default one.
I' have replaced all the input used in tests that not require a role with input of `type=password` that doesn't have a 
default role @benmonro 
2) I have skipped generic role because we prefer to suggest others query 
we prefer `screen.getByText(/bob/i)` instead of `screen.getByRole('generic', {name: /bob/i})`
**Checklist**:
> fix: Don't recommend ByRole if role is `generic`

- src/__tests__/element-queries.js
Resolves https://github.com/testing-library/dom-testing-library/pull/664#discussion_r444028138
**What**:
No code changes
**Why**:
#664 reatained some outdated code comments that were made obsolete with that PR
**How**:
Remove comments
**Checklist**:
- ~[ ] Tests~
- ~[ ] Typescript definitions updated~
> chore: remove outdated code comments

- src/__tests__/fake-timers.js
- src/wait-for.js
**What**: fix(waitFor): handle odd timing issue with fake timers
**Why**: It's super hard to explain and I honestly don't really understand the issue completely myself. All I know is, before moving the `checkCallback` function call above the promise flush line, I had issues with tests impacting each other. After this change, that issue goes away.
I also added a comment explaining why we shouldn't use `jest.advanceTimersToNextTimer` along with a test to demonstrate the issue.
**How**: Change the order of operations
**Checklist**:
~- [ ] Documentation added to the [docs site](https://github.com/testing-library/testing-library-docs) N/A~
~- [ ] Typescript definitions updated N/A~
> fix(waitFor): handle odd timing issue with fake timers

- types/config.d.ts
**What**:
- adds the `getConfig` type to the TS typings
**Why**:
- otherwise it seems that `getConfig` isn't exported
**How**:
- add it to type types file
**Checklist**:
> fix: add getConfig to types

- src/__tests__/base-queries-warn-on-invalid-container.js
- src/__tests__/fake-timers.js
- src/__tests__/wait-for-element-to-be-removed.js
- src/__tests__/wait-for.js
- src/wait-for.js
- types/wait-for.d.ts
**What**: add onTimeout which adds DOM output to timeout errors
**Why**: Closes #559 (nicer error messages)
**How**: add the parameter and have it use prettyDOM to attach the nice message to the error
**Checklist**:
> feat(waitFor): add onTimeout which adds DOM output to timeout errors

- src/__tests__/suggestions.js
- src/suggestions.js
**What**:  Fix a little bug 
**Why**:  As reported [here](https://github.com/testing-library/testing-playground/issues/214) when `getSuggestedQuery` tried to get label text through `aria-labelledby` it threw an exception when the id had spaces or special chars
**How**: Surrounding the selector with `" "`
**Checklist**:
> fix: use the first label for LabelText query suggestions

- src/__tests__/role.js
- src/queries/role.js
**What**:
The getByRole queries are designed to return a single element whose role matches the provided role argument and whose accessible name matches the provided name argument.
When multiple elements are matched, the language in the error message only mentions the role and not the accessible name.
**Sample query**
```js
screen.getByRole('definition', { name: /value/i })
```
**Current error message**
```
TestingLibraryElementError: Found multiple elements with the role "definition"
```
**New error messages**
```
TestingLibraryElementError: Found multiple elements with the role "definition" and name "value"
```
```
TestingLibraryElementError: Found multiple elements with the role "definition" and name `/value/i`
```
**Why**:
When you have several queries against the same role but for …
> Adds matcher name to multiple elements error

- src/__tests__/role.js
- src/queries/role.js
- src/query-helpers.js
**What**:
This PR adds the found elements to the log output of the MultipleError
**Current error**
```
TestingLibraryElementError: Found multiple elements with the role "definition"
```
**New error**
```
TestingLibraryElementError: Found multiple elements with the role "definition"
<dd
aria-labelledby="uid-4-propertyValue"
class="mb-0 text-size-large"
>
565000           
</dd>
<dd
aria-labelledby="uid-4-appraisedValue"
class="mb-0 text-size-large"
>
None         
</dd>
<dd
aria-labelledby="uid-4-appraisedValue"
class="mb-0 text-size-large"
>
2240 sqft         
</dd>
```
**Why**:
It's not always immediately obvious which elements are conflicting, and since dom-testing-library needs to find them in order to know there are multiples it makes sense to expose that to the user
**How**:
I'm …
> Lists elements that matched multiple error

- src/__tests__/wait-for.js
**What**: 
I fixed typo in wait-for test.
**Why**:
**How**:
**Checklist**:
> Fixed typo in wait-for test

- src/__tests__/suggestions.js
- src/suggestions.js
fix #693 
**What**: I have escaped all queries
**Why**: Because string with special chars should be escaped to be used with regex
**How**: I have simply called `escapeRegExp` in `getRegExpMatcher`  
**Checklist**:
> fix: escape regexps that are used as query suggestion arguments

- package.json
**What**:
Closes #685
**Why**:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title#:~:text=The%20element%20provides%20an,display%20it%20as%20a%20tooltip.
**How**:
Propagate https://github.com/eps1lon/dom-accessibility-api/pull/324 to library dependents.
**Checklist**:
- ~[ ] Documentation added to the~
- ~[ ]~ Tests (tested in dom-accessibility-api)
> fix: Consider title for name of svg element

- src/__tests__/ariaAttributes.js
- src/queries/role.js
- src/role-helpers.js
- types/queries.d.ts
Closes #691 
**What**:
Allow querying checkboxes and radios that are checked using the `selected` option in `ByRole` queries.
**Why**:
Better experience than filtering for them
**How**:
Checking for both `aria-selected` _and_ `checked` property.
**Checklist**:
> support `{checked: true}` for checkbox / radio

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**:
- `input` elements with not empty value are retrieved by `getAllLabelsByText`
- `getByLabelText` gets labels even when it receives a label composed of a concatenation
**Why**:
Issue #545 finds out that `input` elements are not recognized as labels and  labelling by concatenation is not got by `getByLabelText`.
**How**:
1. `queryAllLabelsByText` now makes a query not only on elements of type 
label but on input elements too. The empty input are excluded.
2. after evaluating labels node through `matcher`, the labels that doesn't match are combined through an helper function. If a combination matches with the received text than the labels is returned by `queryAllLabelsByText`. 
**Checklist**:
I have already opened …
> get by label concat values

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**: When using aria-labelledby, getByLabelText should account for a selector that might need quotes around it.
**Why**: In such a case, the selector is invalid causing unexpected test failures 
**How**: Just a one line change to wrap quotes around the id in the selector.
**Checklist**:
Closes https://github.com/testing-library/dom-testing-library/issues/707
> Issue 707- getByLabelText does not work with some IDs when using aria-labelledby

- src/__tests__/element-queries.js
- src/queries/label-text.js
**What**:
This should fix #710. 
**Why**:
#681 introduces a bug that makes code fails if an element's `aria-labelledby` attribute has a value not existing in dom as element id .
**How**:
**Checklist**:
> fix aria-labelledby with not found id 

- src/__tests__/matches.js
- src/matches.js
**What**:
Added a nice explicit error message for the case in #717 of `null` or `undefined` as a `matcher`.
**Why**:
Better error messages = happier users! 💝
**How**:
**Checklist**:
As before: I'm not attached to this particular error message, if a reviewer can think of something better that'd be nice.
> Added explicit error message for null or undefined matchers

- src/__tests__/element-queries.js
- src/queries/label-text.js
- tests/setup-env.js
**What**: 
`*ByLabelText` is updated to support IE11 and other legacy browsers.
**Why**:
Closes #723.
**How**:
`HTMLInputElement.prototype.labels` is polyfilled. [Existing test covering primary use cases of getByLabelText](https://github.com/testing-library/dom-testing-library/blob/2c57f06cf76a3f388e943628de7aba6eb5d6afe1/src/__tests__/element-queries.js#L147) is copied into a new test, where the `labels` property is mocked to simulate absence of support.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)~ N/A
This PR stops short of polyfilling `HTMLLabelElement.prototype.control`, which [appears to be well-supported](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control#Browser_compatibility) in older browsers.
> fix(ByLabelText): support IE and other legacy browsers

- src/__tests__/ariaAttributes.js
- src/queries/role.js
- src/role-helpers.js
- types/queries.d.ts
Hat tip to Sebastian Silbermann for his prior work on PR #692
**What**: Adds support for querying based on `aria-pressed` state for elements with a role of "button" (see https://www.w3.org/TR/wai-aria-1.1/#aria-pressed)
**Why**: `aria-checked` and `aria-selected` area already supported; adding the ability to query by `aria-pressed` should round out support for querying by these types of parameters.
**How**: This is implemented in exactly the same fashion as Sebastian Silbermann's implementation in PR #692.
**Checklist**:
> feat(role): support `{pressed: true}` for buttons

- package.json
- src/__tests__/role.js
- src/config.js
- src/queries/role.js
- src/role-helpers.js
- src/suggestions.js
- types/config.d.ts
This change is backwards incompatible if you're using `@testing-library/dom` in a browser.
**What**:
Ignore `::before` and `::after` for accessible name computation by default.
Closes #735
**Why**:
`jsdon@^16.4.0` logs console error if the second argument in `getComputedStyle` is specified.
**How**:
- tell `dom-accessibility-api` the the second argument isn't supported
- add a config option to re-enable that behavior (recommended if you're using testing-library in a browser
**Checklist**:
Will be using release version of `dom-accessibility-api` later. We can discuss first if the current approach is acceptable in `@testing-library/dom`.
> fix: Ignore pseudo elements for accessible name by default

- src/__tests__/events.js
- src/events.js
**What**:
Change the logic of copying `dataTransfer` props
**Why**:
At the moment `Object.assign` is used  to extend event object with passed data, but doesn't copy non-enumerable props
**How**:
In order to iterate by non-enumerable props `getOwnPropertyNames` method is used
**Checklist**:
> Copy non-enumerable data transfer props

- package.json
- src/__tests__/role.js
fix #747 
**What**: This PR will update dom-accessibility-api to the latest version
**Why**: Because in the new version there is a fix for the issue.
The update will solve a problem where title should be ignored when is empty while using name option
**How**: 
**Checklist**:
> fix: update dom-accessibility-api

- src/__tests__/element-queries.js
- src/queries/title.js
Fix #741 
**What**: The `getByTitle` query was meant to match the `title` attribute or `svg > title` element. The logic was implemented that it would also match the text content of any element containing a `title` attribute.
**Why**: We want to correct the behavior of the query. It should only match text content of the `svg > title` element and not any element with a `title` attribute.
**How**: Add a condition of the text content matcher to ensure the node we are checking is `svg > title` element.
**Checklist**:
> fix: getByTitle returning element matching textContent instead of title

- types/config.d.ts
Closes #761
Actual name: https://github.com/testing-library/dom-testing-library/blob/741096b5763c850ae26441343e14f83034231946/src/config.js#L21
> fix: fix typo in config type properties

- src/event-map.js
**What**:
Fix `gotpointer` and `lostpointercapture` not bubbling
**Why**:
- Not spec-compliant (see https://www.w3.org/TR/pointerevents/#attributes-and-default-actions)
- Results in React event listeners not being triggered 
Failing with current version of DTL: https://travis-ci.org/github/testing-library/react-testing-library/jobs/726794155#L289-L323
Passing with this PR: waiting for codesandbox
**How**:
Fix entry for `gotpointercapture` and `lostpointercapture` in `event-map`
**Checklist**:
- ~[ ] Tests~
- ~[ ] Typescript definitions updated~
> fix(events): got-/lostpointercapture bubble

- types/wait-for-dom-change.d.ts
- types/wait-for-element.d.ts
- types/wait.d.ts
For warning TS users early.
How it looks in 'VS Code':
> fix: Mark deprecated methods as `@deprecated`

- types/__tests__/type-tests.ts
- types/events.d.ts
fix #775
**What**: fix typescript type
**Why**: It was not correct, because you can create custom Event using `createEvent` function
**How**:
**Checklist**:
> fix: createEvent type

- src/__tests__/wait-for.js
- src/query-helpers.js
- src/wait-for.js
**What**: Using `getElementError` from configuration in `waitFor` and `singleQuries` so that user can customize error reporting consistently.
**Why**: Currently when configuring getElementError it works differently in for example `getByText` vs `waitFor(() => getByText)`.  
**How**: Instead of calling prettyDOM directly I changed it so that it uses `getElementError` from configuration.
**Checklist**:
> fix: element error delegation

- src/__tests__/wait-for.js
- src/wait-for.js
- types/__tests__/type-tests.ts
- types/wait-for.d.ts
You can now return a promise in the waitFor callback and your callback
will not be called again until the promise rejects. If the promise
rejects, then the callback will be called again until it gets a promise
which resolves or it times out.
**What**: feat(waitFor): allow returning a promise
**Why**: So we don't have to do weird things like this: https://github.com/kentcdodds/bookshelf/pull/83/files#diff-f3caa0e4f827bc632c53d30ddb2aeb60R26-R29
Specifically, we need to `waitFor` something, but the callback has to do something asynchronous to determine whether we can continue our test. Today, `waitFor` does not support this... Until now...
**How**: Store a promiseStatus and if the waitFor callback returns a "thennable" then we attach our own handler onto the promise and update the …
> feat(waitFor): allow returning a promise

- package.json
- src/__tests__/screen.js
- src/screen.js
- types/screen.d.ts
> feat: add logPlaygroundUrl in screen

- src/__tests__/element-queries.js
- src/get-node-text.js
- src/helpers.js
- src/queries/label-text.js
**What**: I have fixed #787 and the comment in https://github.com/testing-library/dom-testing-library/issues/343#issuecomment-555385756
**Why**: Because following specs it should be possible to get `output` by it's label. 
**How**: Instead of replacing string that could cause the issue in the comment https://github.com/testing-library/dom-testing-library/issues/343#issuecomment-555385756 I have looped al the childNodes taking text only from the right nodes
**Checklist**:
> fix: getByLabelText for output

- types/__tests__/type-tests.ts
- types/query-helpers.d.ts
**What**: Updated types for built findBy / findAllBy custom queries and added extra type tests
**Why**: A fix made in PR #574 / Issue #534 added these parameters but accidentally made them required (see https://github.com/testing-library/dom-testing-library/pull/574#issuecomment-629213137)
**How**: Updated the types in `query-helpers.d.ts` to mimic the built-in types in `queries.d.ts`, and added more type tests to ensure it won't regress.
**Checklist**:
> fix(types): make third and fourth params optional for findAllBy and findBy built queries

- .huskyrc.js
- src/wait-for.js
Here is a little PR after opening this issue https://github.com/testing-library/dom-testing-library/issues/800
(my investigation is on it)
**What**:
My test are slow because of MutationObersion disconnections made at the end of my tests.
**Why**:
Currently `observer.disconnect()`is called in setImmediate, I guess the main thread is not available until the end of the test, so the check callback is called too much times.
This was done in this PR #102 
**How**:
All my explanations are visible here: https://github.com/testing-library/dom-testing-library/issues/800#issuecomment-720140316
After making many test, I didn't see any problem to call both: 
```
setImmediate(() => observer.disconnect());
observer.disconnect();
```
**Checklist**:
[docs …
> Disconnect MutationObserver synchronously in wait-for

- src/__tests__/label-helpers.js
- src/__tests__/queries.find.js
- src/label-helpers.js
**What**:
This PR ensures `*LabelText` helpers do not throw an error when there are hidden inputs.
**Why**:
The `labels` property on `input` elements of type `hidden` is [`null` rather than `NodeList`](https://html.spec.whatwg.org/multipage/forms.html#dom-lfe-labels). This meant the `getRealLabels` function would return `null` causing `queryAllByLabelText` to throw an error when it tried to [call `length` on `null`](https://github.com/testing-library/dom-testing-library/blob/62f4e5e09a4b81ef66679560b540523edccdef98/src/queries/label-text.js#L52).
I noticed this issue when using `cy.findByLabelText` (from [@testing-library/cypress](https://github.com/testing-library/cypress-testing-library)) – which fails with the following exception on pages with hidden inputs:
```
Timed out retrying: …
```
> Fix null labels on hidden inputs

- .github/workflows/validate.yml
- README.md
- Don't run release on forks
- Use `semantic-release@17.x`
> chore(validate): Update validate workflow

- .github/workflows/validate.yml
- package.json
- types/tslint.json
**What**: This updates all deps and adds `@types/estree` to avoid dedup issues
**Why**: The build was broken. More info: https://github.com/rollup/plugins/pull/639
**How**: Update all deps and add `@types/estree` temporarily
**Checklist**:
> chore: upgrade all deps and fix the build

- src/pretty-dom.js
- types/pretty-dom.d.ts
**What**: referring to this issue https://github.com/testing-library/react-testing-library/issues/694 I have exported `pretty-format` from this library
**Why**: Because we can then import in `@testing-library/react`
**How**:
**Checklist**:
> fix: export pretty format

- src/__tests__/role.js
- src/role-helpers.js
**What**: close #814 
**Why**: It was a bug
**How**: Adding an exception for type=text.
Instead of using the selector I have used the node property.
**Checklist**:
> fix: use node property instead of selector for type=text input

- src/__tests__/element-queries.js
- src/matches.js
- types/__tests__/type-tests.ts
- types/matches.d.ts
**What**: TextMatch is allowed to be of any non-nullable type (`any` except `undefined` and `null`)
**Why**: Error messages show confusing failed method calls instead of attempting to treat the TextMatch as a string implicitly (fixes #826)
**How**: Call `String()` whenever the TextMatch matcher isn't a `RegExp` or `Function` (allowing it to be `any` instead of `string`)
**Checklist**:
> feat: allow TextMatch to be any non-nullable type

- src/__tests__/suggestions.js
- src/suggestions.js
**What**:
Console warnings are being emitted, even when they shouldn't be.  For example, if you're using getByRole, you shouldn't see a warning about it, only when the suggestion is actually used.
**Why**:
causes noise in test runs.
**How**:
by moving the console.warn into the toString() which is only used when the suggestion is thrown.
**Checklist**:
> fix(suggestions): only warn about inaccessible elements when actually showing the suggestion

- src/__tests__/fake-timers.js
- src/__tests__/wait-for.js
- src/wait-for.js
- tests/setup-env.js
**What**: feat: warn when the test environment fake timers change unexpectedly
**Why**: Closes: #830 
**How**: For every iteration of waitFor, it checks whether the state of fake timers has changed and if it has, it rejects with an error. Also supports the `showOriginalStackTrace` config option.
**Checklist**:
> feat: warn when the test environment fake timers change unexpectedly

- src/__tests__/suggestions.js
- src/queries/label-text.js
**What**: a bug fix on suggestions for findByLabelText
**Why**: when using findByLabelText, you would get a suggestion even if you're already using findByLabelText.
**How**:  use the right function when passing the name of the method.
**Checklist**:
> fix(suggestions): don't suggest byLabelText when using byLabelText

- src/matches.ts
- types/matches.d.ts
- types/tsconfig.json
**What**:add number support for matches
**Why**: because of an issue with typescript configuration I have dropped the support in #848 
**How**:
**Checklist**:
> fix: add number support for matches

- src/__tests__/text-matchers.js
- src/queries/label-text.js
**What**:
fixed the label matcher - so that it passes on the normalizer when matching the aria-label, added a test too
see #854 
**Why**:
because the normalizer wasn't being correctly passed on
**How**:
see - src/queries/label-text.js
**Checklist**:
-  I did opt in to run git hooks - but had some issues with the `validate` script - it just seemed to error and not output anything useful so I ended up bypassing it.
- Also - all the tests in src/__tests__/text-matchers.js were named after a method. Because `...byLabelText` can get the label in multiple ways - and I wanted a specific test for the aria-label case - I've added a case that isn't named after a specific method
> fix: add normalizer for matching aria-label

- src/__tests__/wait-for-element-to-be-removed.js
- src/wait-for-element-to-be-removed.js
**What**:
Fixes #870. 
**Why**:
Utility method `waitForElementToBeRemoved` should not crash when given element is already removed from its parent element. It should handle these cases and clearly report element is already removed. 
**How**:
Check whether element has `.parentElement` before accessing it. Prevents unexpected null pointer. 
**Checklist**:
I was unable to use the pre-commit hook. The `kcd-scripts test --findRelatedTests` keeps running forever. After 10-15mins I cancelled it and commited with `--no-verify`. Same thing has happened to me before with `@testing-library/eslint-plugin-jest-dom` repository.
Here's output of the test case **without the fix applied** just to indicate the error is same as in #870. …
> fix: prevent crashing on elements without parentElement

- src/__tests__/helpers.js
- src/helpers.js
**What**:
Rewritten `runWithRealTimers` and the related tests.
**Why**:
`runWithRealTimers` activated fake timers when a `jest.useFakeTimers('modern')` has been used in any test before.
The tests leaked `setTimeout`.
See #884 and #886
**How**:
Call `jest.useRealTimers` and check if any timer functions changed to determine if fake timers have been active.
**Checklist**:
- N/A Documentation added to the
- N/A Typescript definitions updated
> fix: remove side-effect from runWithRealTimers

- .github/workflows/validate.yml
**What**:
Fixes missing codecov reports in PRs
**Why**:
These are required for PRs to be mergable. Right now only admins can merge.
**How**:
Set `fetch-depth` to `0` [as suggested](https://github.com/testing-library/dom-testing-library/pull/858/checks?check_run_id=1837616294#step:7:22)
I also changed the action so that it fails CI on failure. Otherwise it's not obvious why the check is missing.
Added `flags` while we're at it to know where coverage might be missing.
**Checklist**:
> chore: Fix missing codecov report in PRs

- src/helpers.js
- src/wait-for.js
**What**:
Closes #898
**Why**:
`callback` might mock timers or timers might be mocked in another way. 
**How**:
Check if we're in a `jest`-like environment via `typeof jest !== 'undefined'`.
**Checklist**:
> fix: Don't assume mocked timers imply jest fake timers

- src/__tests__/helpers.js
- src/helpers.js
**What**: New error message when passing an Array.
**Why**: This can be a quick typo when using `screen.getAll*` or `screen.queryAll*` queries. 
**How**: Type checking for `Array`.
**Checklist**:
> feat: Improve error message when passing an Array while a single Element is expected

- CONTRIBUTING.md
**What**:
Removes out-dated instructions about `.opt-in` file. 
**Why**:
Support for `.opt-in` was droppped in `kcd-scripts@5.0.0`: https://github.com/kentcdodds/kcd-scripts/pull/119.
This section should have been removed in https://github.com/testing-library/dom-testing-library/pull/447.
**How**:
\- 
**Checklist**:
Ran into this issue when studying why pre-commit hooks of all testing-library repositories get stuck in my environment. This wasn't the root cause though - I'll keep debugging.
> docs: remove outdated pre-commit instructions

- src/__tests__/helpers.js
- src/helpers.js
**What**:
Avoid crashing when `setImmediate` and `clearImmediate` is not defined, which is now the case for JSDOM.
**Why**:
See #914 
**How**:
Safe check suggested by @gaearon
**Checklist**:
> Safe check for setImmediate and clearImmediate

- types/query-helpers.d.ts
**What**: Add missing `ignore` parameter definition in type `SelectorMatcherOptions`. 
From the [docs](https://testing-library.com/docs/queries/bytext/#ignore) and the codebase it looks like it can either be a string or a boolean.
**Why**: Resolves https://github.com/testing-library/dom-testing-library/issues/921
**How**: Added the missing parameter manually.
**Checklist**:
> fix(types): missing ignore parameter for SelectorMatcherOptions

- src/helpers.js
**What**:
Check if `jest.useRealTimers` is a function before calling it.
Closes #905 
**Why**:
In some environments (e.g. codesandbox) `jest` exists but is either `null` or the `useRealTimers` and `useFakeTimers` don't exist.
**Checklist**:
- N/A Documentation added to the
- N/A Tests
- N/A Typescript definitions updated
> fix: Guard against `jest.useRealTimers` not existing

- src/label-helpers.ts
- src/matches.ts
- src/queries/label-text.ts
- types/matches.d.ts
- types/query-helpers.d.ts
**What**:
Remove `Nullish` helper type
**Why**:
Seems to be unused. So if we don't need the helper type let's remove the indirection.
**How**:
Replace usage of `Nullish<T>` with `T | null`.
**Checklist**:
- ~[ ]~ Tests
> chore: Remove unused Nullish type

- .github/ISSUE_TEMPLATE.md
- .github/workflows/validate.yml
- CONTRIBUTING.md
- package.json
- src/event-map.js
- src/wait-for-element-to-be-removed.js
- types/get-node-text.d.ts
- types/index.d.ts
- types/wait-for-dom-change.d.ts
- types/wait-for-element.d.ts
- types/wait.d.ts
**What**:
- format codebase 
- fail CI if changed code isn't formatted (proof-of-concept: https://github.com/testing-library/dom-testing-library/runs/2519546268)
**Why**:
Codeformat is beginning to drift. It adds noise to PRs if unrelated code looks like it changed at first glance.
**How**:
- `npm run kcd-scripts format` locally
- `npm run kcd-scripts format -- --check` in CI
**Checklist**:
> chore: Format codebase with prettier

- package.json
**What**:
Closes https://github.com/testing-library/dom-testing-library/issues/866
**Why**:
`<output />` is labelable
**How**:
Bump `dom-accessibility-api` to include https://github.com/eps1lon/dom-accessibility-api/pull/666
**Checklist**:
- ~[ ]~ Tests (tested in https://github.com/eps1lon/dom-accessibility-api/pull/666)
> fix: Consider `<output />` labelable

- .codesandbox/ci.json
- .github/workflows/validate.yml
- package.json
BREAKING CHANGE: node 10 is no longer supported. It reached its end-of-life on 30.04.2021.
**What**:
Closes https://github.com/testing-library/dom-testing-library/pull/975
Closes https://github.com/testing-library/dom-testing-library/issues/957
**Why**:
Reduces maintenance burden
**How**:
Change `engines` field to require `node>=12`
**Checklist**:
Will do once we release the alpha
> feat: Drop support for node 10

- src/__tests__/fake-timers.js
Identified the bug when trying out v8 alpha in react-spectrum. Waiting for release of https://github.com/facebook/jest/pull/11567
**What**:
Add a test for a bug caused by https://github.com/facebook/jest/issues/11565
**Why**:
Hoping that we can work around this bug in any way. Would appreciate if anybody got some insight.
**How**:
Add a test when where we `waitFor` `requestAnimationFrame`
**Checklist**:
> test(waitFor): Add current behavior for legacy fake timers and requestAnimationFrame

- types/pretty-dom.d.ts
**What**:
In response to https://github.com/testing-library/dom-testing-library/pull/979#issuecomment-862974030. Follow-up to https://github.com/testing-library/dom-testing-library/pull/907
**Why**:
These options are passed to `prettyDOM` not `pretty-format`
**How**:
Rename PrettyFormatOptions -> PrettyDOMOptions
**Checklist**:
- ~[ ]~ Tests
> chore: PrettyFormatOptions -> PrettyDOMOptions

- src/__tests__/fake-timers.js
**What**:
Fix tests.
**Why**:
To be able to release
**How**:
Normalize requestAnimationFrame related tests across legacy and modern timers after https://github.com/facebook/jest/pull/11567 was released
**Checklist**:
> test(fake-timers): raf is now mocked in legacy fake timers

- src/__tests__/events.js
- src/event-map.js
- types/events.d.ts
**What**:
Closes https://github.com/testing-library/dom-testing-library/issues/179 (was closed without adding resize event)
**Why**:
Enables automatic wrapping of resize events with `act` in /react via `fireEvent.resize`.
**How**:
Add the appropriate config. There's no verification for the event target since we never check if the event target is valid.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) (Documentation points to source)
> feat(fireEvent): Add resize event

- src/events.js
**What**:
Fix CI on `main` (e.g. https://github.com/testing-library/dom-testing-library/runs/3419566094)
**Why**:
No longer able to ignore the condition with Istanbul. 
This was always an issue (https://github.com/gotwarlost/istanbul/issues/781) but it seems like some updated dependency broke the previous workaround. Since we don't use lockfiles, we can't investigate when and why.
**How**:
Use "lonely-if" instead of `else-if`
**Checklist**:
> test: Fix missing coverage for else-if

- src/__tests__/element-queries.js
- src/get-node-text.ts
**What**:
Currently doing `screen.getByText('Reset')` results in an error about being unable to find the text if you're testing for an input like so:
```
export const Form: React.FC<Props> = props => (
<form onSubmit={props.onSubmit} onReset={props.onReset}>
{props.children}
<br />
<input type="submit" value="Submit" />
{props.onReset && <input type="reset" value="Reset" />}
</form>
);
```
But this works fine if you try and select the "submit" input in the same manner: `screen.getByText('Submit')`
**Why**:
https://github.com/testing-library/dom-testing-library/pull/185 added support for treating inputs of type `submit` & `button` as if they have text, but it left out `reset` which is the third "type" that has this behaviour.
**How**:
I've adjusted the query to include `type=reset`. …
> fix: support getting text of inputs of type `reset`

- package.json
- src/__tests__/get-user-code-frame.js
- src/screen.ts
**What**:
Converting the following to TS:
* `src/screen.js` -> `src/screen.ts`
**Why**:
#494 outlines motivations and status of project TS conversion, for which this is the start of my contribution.
**How**:
Renamed file. Found type errors and started to fix them whilst trying to keep runtime logic intact.
**Checklist**:
0. Should I squash my commits?
1. Do TS defs need to be updated? From what I understand `kcd-scripts` builds d.ts files from the `npm run build` script.
2. I had some coding style/type strictness questions that I've described in the form of "Grok Flow", at this link:
https://dev.app.trygrok.com/pl/YQHa2AMeAQAeanwo/imO5GqKqQI-sE1jrFFUWjg
It's a mind-map style format for describing code-adjacent …
> chore: Convert screen.js to TypeScript

- src/__tests__/element-queries.js
- src/__tests__/pretty-dom.js
- src/config.ts
- src/pretty-dom.js
**What**:
This PR brings back the `prettyDOM` logging when the library is used within a cypress test (including from within cypress-testing-library)
**Why**:
https://github.com/testing-library/cypress-testing-library/issues/172
Back in 2018, a decision was made to remove prettyDOM logging when used within a Cypress test. This was done because Cypress's default subject is the full document, and pretty-printing the `outerHTML` of the entire document would occasionally cause memory errors. 
This change was made here- https://github.com/testing-library/dom-testing-library/pull/336/files#diff-2a50dc385b740f1ed6423e95977cc8dcccced5b7d8088e1dd7a02d062872cf1eR18-R19
Discussion around the decision is here - https://github.com/testing-library/dom-testing-library/issues/44#issuecomment-392287703 …
> Restore prettyDOM logging for Cypress

- .github/workflows/validate.yml
**What**:
The validate pipeline previously immediately stopped once a single job failed. Now we complete every job even if another fails.
**Why**:
This made it impossible to know if an issue is invariant across the test matrix or tied to a specific value.
**How**:
Disable `fail-fast`
**Checklist**:
- ~[ ]~ Tests
> test: Run full matrix even if a single job fails

- .github/workflows/validate.yml
**What**:
Fix GitHub jobs using node 16
**Why**:
They're currently broken due to using the cached and broken node version 16.9.0 which causes jest to fail due to
**How**:
Cherry-pick using a working version which works in a previously failing job: https://github.com/testing-library/dom-testing-library/runs/3574134403
**Checklist**:
> test: Ensure broken node 16.9.0 isn't used

- .github/workflows/validate.yml
- types/query-helpers.d.ts
**What**:
Closes https://github.com/testing-library/dom-testing-library/issues/1025
**Why**:
https://github.com/testing-library/dom-testing-library/pull/1016 introduce syntax that's not compatible with older TypeScript versions.
**How**:
Don't label tuple members.
**Checklist**:
> fix: Use syntax compatible with older TypeScript versions

- types/__tests__/type-tests.ts
- types/query-helpers.d.ts
**What**:
> The types for the arguments to GetErrorFunction are stuck at the default. At runtime, you can log `...args` and see that the expected key and value are passed.
**Why**:
Described in [this issue](https://github.com/testing-library/dom-testing-library/issues/1037).
**How**:
Passed `Argument` generic to `GetErrorFunction` in `buildQueries` type definitions
**Checklist**:
> fix(buildQuery): get*Error functions receive same Arguments type as queryAllBy parameter

- package.json
- src/__tests__/__snapshots__/role-helpers.js.snap
- src/__tests__/element-queries.js
- src/__tests__/pretty-dom.js
- src/__tests__/role.js
- src/__tests__/screen.js
- src/__tests__/suggestions.js
- src/__tests__/wait-for.js
- tests/setup-env.js
**What**:
Two snapshot tests were failing locally while passing on CI, this change fixes it so that tests are green on CI as well as locally.
The replaced library was appending extra double quotes at the begging and end of the string.
https://github.com/joaogranado/jest-serializer-ansi/blob/c8c5e8cbc0f804f9fe195dfd27625ea0b3d2a062/index.js#L13-L16
**How**:
Replacing jest-serializer-ansi library with jest-snapshot-serializer-ansi.
**Checklist**:
> test: Fix inline snapshot mismatch on certain machines

- types/__tests__/type-tests.ts
**What**:
Follow up to #1034
**Why**:
I wanted to add generics to the within queries, but they already accept a generic.
I think adding a few tests could be helpful for potential changes in the future. 
**How**:
Added a few tests and saw that the tests were passing
**Checklist**:
cc @nstepien
> test: add type tests for within

- types/__tests__/type-tests.ts
- types/get-queries-for-element.d.ts
**What**:
Adds custom query types if `within` adds custom and base (`queries`) queries.
**Why**:
https://github.com/testing-library/dom-testing-library/pull/1034 broke the previous untested behavor.
**How**:
Intersect with custom queries.
**Checklist**:
> fix(within): Types should list custom and base queries

- src/queries/role.js
**What**:
Related to https://github.com/testing-library/dom-testing-library/issues/698 and https://github.com/testing-library/dom-testing-library/issues/820.
`*ByRole` queries are filtering inaccessibility (`hidden: false`) earlier than accessible names. This PR changes that by prioritizing accessible names over inaccessibility. Hopefully to achieve better performance in most cases.
**Why**:
As stated in https://github.com/testing-library/dom-testing-library/issues/820#issuecomment-726936225, one of the _escape hatches_ to improve the performance of the `*ByRole` queries is to pass `hidden: true` to the options. The reason is that the visibility check is more expensive in most cases. People are already using this technique to improve their queries' performance by setting the default …
> feat: Prioritize accessible names check higher than inaccessibility check in `byRole` queries

- src/__tests__/wait-for.js
- src/wait-for.js
**What**:
Fixes integration with of `@testing-library/react@alpha` in React Spectrum when using React 18.
**Why**:
Otherwise context restoration in `unstable_advanceTimersWrapper` becomes unpredictable leading to fixes like [`d375ff3` (#2526)](https://github.com/adobe/react-spectrum/pull/2526/commits/d375ff359347d7818ed4902f3e37281bb7b5d61e#diff-c19475ebc27556f4091d71e843529459da93e9ebe0179c9650978422ec3b2942L2099-R2099) that seemingly have nothing to do with the test/implemenation but magically fix tests.
The implementation change fixed 
```js
it('should handle when a non drop target element is added', async () => {
let setShowInput2;
let Test = () => {
let [showInput2, _setShowInput2] = React.useState(false);
setShowInput2 = _setShowInput2;
return (<>
<Draggable />
<input />
<Droppable …
```
> fix(wait-for): Don't queue microtasks after condition is met

- types/__tests__/type-tests.ts
- types/get-queries-for-element.d.ts
**What**:
Closes https://github.com/testing-library/react-testing-library/issues/979
TS error occurs when reassigning the return value of `within`
```typescript
import { screen, within } from "@testing-library/dom";
import "@types/jest";
import "@testing-library/jest-dom";
const navigation = screen.getByRole("navigation");
let breadcrumbs = within(navigation);
expect(breadcrumbs.getByRole("link", { name: /home/i })).toBeInTheDocument();
// ts error occurs
breadcrumbs = within(navigation);
```
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwMZQKYYHYBo4DuwMAFsNnAL5wBmUEIcARAAIwbIzkDmAtADbAARlACGUAJ4B6ACYMmAbgBQoSLGZsJYDlIBWHGIpXho8Vu048BwsZL0HeckEaWoI2TnGyiAbsG6iXO5wALwo6FjYAHTcGDAAQhIAShD8GAAUTN5+AUHYTACUymnwIhiiMugAriBCyKGExGTY6dn+gcDuRUoYAB7aqDDpZRXVtcgxcYkpaZmC2ADWTPhI3iAYAF …
> fix(within): Add extra type paramater to allow reassigning in TypeScript

- .codesandbox/ci.json
- package.json
Ports https://github.com/testing-library/react-testing-library/pull/1020 to this repository. 
We're experiencing the same issue with codesandbox in https://ci.codesandbox.io/status/testing-library/dom-testing-library/pr/1112/builds/229879
> chore: Fix failing codesandbox/ci

- src/__tests__/events.js
**What**:
I noticed when running the tests that the `fires resize` test was defined within the `forEach` above, meaning it was running for every `eventType` item.
**Why**:
Remove redundant duplicate test runs.
**How**:
**Checklist**:
> test: move resize test outside of forEach

- src/__tests__/matches.js
- src/matches.ts
**What**: Resolves #1115
**Why**: 
The instance of a regex that's using the global flag hold a `lastIndex` state.
This might give false positive results.
For example:
```
const g = /foo/g
g.test('foo') // |> true
g.test('foo') // |> false because lastIndex is 3
g.test('foo') // |> true because lastIndex is 0 again
g.test('foo') // |> false because lastIndex is 3
```
**How**:
Added a reproduction test case.
Recreate a new regex instance from the original regex.
An alternative would be to reset the `lastIndex` to `0` after the check.
**Checklist**:
> fix: reset regexg to prevent regexg with global flags to not match every element

- src/__tests__/role.js
- src/queries/role.js
- src/role-helpers.js
- types/queries.d.ts
**What**:
Add a new `description` option to `ByRole` queries.
This helps finding elements which are aria described.
**Why**:
We were implementing a React component to display the usual popup notifications and, when reading about accessibility considerations, we found we should use `ariadialog` role and we also should use `aria-describedby` to reference the message ([spec documentation](https://www.w3.org/TR/wai-aria-1.1/#alertdialog)).
When writing some tests we wanted to have one where we could close an specific notification when a list of them were rendered in a view.
`ByRole` queries currently support filtering results by accessible name, but no filtering by **accessible description**.
**How**:
Since this project is already using the …
> feat(byRole): Add description filter

- src/queries/role.js
**What**: remove the passed `includeName` argument to `prettryRoles` (based on a recent "discussion" at https://github.com/testing-library/dom-testing-library/pull/1120#discussion_r841955370)
**Why**: `includeName` isn't used `prettyRoles` because we always want to show the role name
**How**: removed the `includeName`
**Checklist**:
> refactor: remove includeName argument

- src/__tests__/element-queries.js
- src/config.ts
- src/pretty-dom.js
- src/queries/text.ts
- src/shared.ts
- src/suggestions.js
- types/config.d.ts
**What**:
Adds `defaultIgnore` config option for `byText` in a similar vein to what already exists with `defaultHidden` for `byRole`.
**Why**:
Allows to set a default `ignore` globally for a project.
**How**:
Adds new config option. Also uses potentially overridden config value in places where the the default const was used before as this seemed to make sense to me.
Is this a change you'd be willing to accept?
If yes, I'd be happy to add docs etc. Thanks! :)
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs): https://github.com/testing-library/testing-library-docs/pull/1088#pullrequestreview-1011701676
> feat: add `defaultIgnore` config option

- src/__tests__/events.js
- src/event-map.js
**What**:
`fireEvent.load` (et. al.)  dispatches a `Event` now instead of `UIEvent`
Adds a test for https://github.com/testing-library/dom-testing-library/issues/498
**Why**:
I imagine that the most common targets are `<img />` and `<script />` and neither of these receive load events as `UIEvent`: https://codesandbox.io/s/react-script-does-not-work-the-way-you-think-it-does-stc66c
**How**:
Changed event type and added tests for `<script />`. Ieft a note that our abstraction doesn't support firing events with different types.
Also  removed the notion of "Image events" from comments. We refer to DOM interfaces in all other cases. But there is no such thing as `ImageEvent`.
**Checklist**: …
> fix: load and error dispatch `Event` instead of `UIEvent`

- src/__tests__/role.js
- src/queries/role.js
**What**:
Resolves: https://github.com/testing-library/dom-testing-library/issues/970
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) - N/A
> feat: add name hint to missing error in find by queries

- src/__tests__/screen.js
- src/screen.ts
- types/screen.d.ts
Adding a return value to logTestingPlaygroundURL function besides the log - Resolves #1125
logTestingPlaygroundURL() used to prints the value directly to the stdout of the running process, 
The values was hidden in the log window
Adding a return statement to the logTestingPlaygroundURL function
**Checklist**:
Will add documentation to testing-library-docs after the PR will be completed.
> feat: add a return value from logTestingPlaygroundURL

- src/screen.ts
**What**:
Closes #995
**Why**:
The ecosystem is annoying
**How**:
Follow advise of error message:
```
SyntaxError: Named export 'compressToEncodedURIComponent' not found. The requested module 'lz-string' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'lz-string';
const { compressToEncodedURIComponent } = pkg;
```
**Checklist**:
- ~[ ]~ Tests
> fix: Don't assume named exports interop

- package.json
- src/helpers.ts
**What**:
Part of #494
**Why**:
To use generated TypeScript declaration files eventually
**How**:
Fairly low level helpers where most types are `unknown`. Uses `any` for pragmatic reasons.
**Checklist**:
> chore: Convert `helpers.js` to TypeScript

- src/__tests__/pretty-dom.js
- src/pretty-dom.js
**What**: 
Add an environment flag that allows turning off of colors from the command line.
**Why**: 
Some environments current flag as "node", but print logs in formats that don't handle colorization which makes reading the logs hard to read.
More details here: https://github.com/testing-library/dom-testing-library/issues/1153
**How**: 
Changed the `isNode` function to `shouldHighlight`, and check for the environment variable before checking for the
**Checklist**:
> feat: Allow disabling colorized debug output

- package.json
**What**:
Closes https://github.com/testing-library/dom-testing-library/issues/1169
**Why**:
A minor release created a build with that contained syntax that we don't support yet.
**How**:
Run `npx browserslist defaults` with a version of `caniuse-lite` that was used at the time of the latest good release. 
That snapshot is now contained in our manifest and ensures build tools transpile to this target.
Having "defaults" as the target environment is too weak of a contract to have. 
Now it's apparent that changing the target environment is considered a breaking change.
We can decide in the next major release what a good matrix for supported runtimes is. 
**Checklist**:
- ~[ ]~ TypeScript …
> fix: Pin supported target environment

- src/__tests__/events.js
- src/event-map.js
- types/events.d.ts
**What**:
Added support for the [offline](https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event) and [online](https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event)
event to fireEvent.
**Why**:
To test code that listens for the events.
**How**:
added events to `event-map.js`
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)  N/A
This is my first contribution so I'm unsure if I did it all right, feel free to provide candid feedback!
> feat: add offline/online events

- .codesandbox/ci.json
- .github/workflows/validate.yml
- package.json
BREAKING CHANGE: Minimum supported Node.js version is now 14.x
**What**:
Drop support for Node.js 12.x
**Why**:
Reached EOL in April 2022. Tooling is starting to drop Node.js 12.x (see JSDOM) as well so it's time to upgrade to be able to test compat with latest test frameworks (e.g. Jest).
**How**:
Targetting alpha for now. Want to batch this with https://github.com/testing-library/dom-testing-library/issues/1202
Look for occurence of "12" and update where appropriate. Also introducing Node.js 18.x into test matrix since that is now in Active LTS
**Checklist**:
> feat: Drop support for Node.js 12.x

- package.json
- src/__tests__/config.js
- src/__tests__/fake-timers.js
- src/__tests__/role.js
- src/__tests__/wait-for-element-to-be-removed.js
- src/__tests__/wait-for.js
- src/helpers.ts
- src/queries/label-text.ts
- src/query-helpers.ts
- src/screen.ts
Blocked by https://github.com/testing-library/dom-testing-library/pull/1207
Stacked on [#1207](https://github.com/testing-library/dom-testing-library/pull/1207) ([Diff against #1207](https://github.com/testing-library/dom-testing-library/compare/eps1lon:feat/drop-node-12...eps1lon:test/kcd-scripts-bump))
**What**:
Bump kcd-scripts to 9.x
**Why**:
Get newer versions of JSDOM
**How**:
Bump kcd-scripts to 9.x
**Checklist**:
> Bump kcd-scripts to 12.x

- package.json
- src/__tests__/suggestions.js
- tests/jest.config.dom.js
- tests/jest.config.node.js
**What**:
Bump kcd-scripts to 13.0.0
**Why**:
Get newer versions of JSDOM
**How**:
Bump kcd-scripts to 13.0.0
**Checklist**:
> Bump kcd-scripts to 13.0.0

- src/__tests__/element-queries.js
- src/__tests__/get-by-errors.js
- src/__tests__/text-matchers.js
- src/queries/role.ts
- types/__tests__/type-tests.ts
- types/matches.d.ts
- types/queries.d.ts
BREAKING CHANGE: Only allow `string` as a `role`.
Drop support for `exact`, `trim`, `collapseWhitespace`, and `normalizer` options.
**What**:
Closes https://github.com/testing-library/dom-testing-library/issues/1202
**Why**:
Options are not needed as far as I can tell. From the tests we have, it seems to me this encourages rather bad queries. Will ship this soon-ish (since it's just an alpha) to test.
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs): https://github.com/testing-library/testing-library-docs/pull/1214
> fix(ByRole): Constrain API 

- .github/workflows/validate.yml
semantic-release posts back to the resolved issues.
Fixes https://github.com/testing-library/dom-testing-library/actions/runs/4198704582/jobs/7282710819#step:7:136
> chore: Allow semantic-release to post updates in issues

- package.json
**What**:
Closes https://github.com/pieroxy/lz-string/issues/147
**Why**:
Ensures the library as a whole is licensed under MIT.
**How**:
Bump lz-string to include https://github.com/pieroxy/lz-string/issues/147
[Changes to published files of lz-string](https://app.renovatebot.com/package-diff?name=lz-string&from=1.4.4&to=1.5.0)
**Checklist**:
- ~[ ]~ Tests
> fix: Ensure MIT licensed lz-string is used

- src/__tests__/suggestions.js
**What**: Add a test that was missing for throwing suggestions
**Why**: While working on the docs requested in the [discussion between](https://github.com/testing-library/testing-library-docs/pull/1214#discussion_r1099027874) @eps1lon and @timdeschryver, I saw that based on the implementation, there's a missing test.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) - N/A
> test: add missing test for suggestions

- src/__tests__/suggestions.js
Brings down the duration of `suggestions.js` tests from ~9s to <1s.
Was always bugging me how sluggish `suggestions.js` tests were. Revisited them during https://github.com/testing-library/dom-testing-library/pull/1215/files and it turns out they're only slow because of real timers. 
However, the test is not concerned with time but the suggesions themselves. I originally just set the timeout to 1 for `find*` queries but this felt noisy and means we might regress in the future.
> test: Improve test perf for suggestion tests

- src/__tests__/ariaAttributes.js
- src/queries/role.ts
- src/role-helpers.js
- types/queries.d.ts
Part of a larger committment to unify APIs for `/react-native` and `/react` (which is just `/react-dom` at the moment)
**What**:
Enables `ByRole(role, { busy })`
**Why**:
Makes writing tests for react-native and react-dom easier by removing barriers when changing the target platform that's being tested.
**How**:
Same patterns as for expanded, selected etc
**Checklist**:
> feat(ByRole): Allow filter by busy state

- src/__tests__/ariaAttributes.js
- src/queries/role.ts
- src/role-helpers.js
- types/queries.d.ts
Part of a larger committment to unify APIs for `/react-native` and `/react` (which is just `/react-dom` at the moment)
**What**:
Enables `ByRole(role, { value })`
Note that we don't support `valuenow` but rather `value.now` (same pattern for other `aria-value*` attributes). One reason is parity with `@testing-library/react-native`. 
The other reason is that `value.*` works a bit different in that it looks at all `value.*` and combines them with `&&` instead of returning on the first match. Today, `{ pressed: true, selected: true}` has kind of an odd behavior since it only looks at whatever comes first in the implementation. We could combine them with `&&` as well but it's not clear to me yet that this is always good. So by putting them in a single object makes it clear that we look at the …
> feat(ByRole): Allow filter by value state

- src/wait-for.js
`unstable_advanceTimersWrapper` now receives an `async` function. If your wrapper just returns the given callback, nothing should break (e.g. this is [not a breaking change for React Testing Library](https://github.com/testing-library/react-testing-library/pull/1205/files). But if you call it first with the expectation that it resolved synchronously, you may observe changed behavior. This method is marked as `unstable_` and not subject to semantic versioning. Still releasing as a feature for safe measure.
**What**:
Add support for having an `async` `unstable_advanceTimersWrapper`
**Why**:
To support experimentation with `async` `act`
**How**:
`await` `advanceTimersWrapper`. This also enables us to flush the microtask queue that exist after the macrotask.
This changes the observed …
> feat(waitFor): Support async `unstable_advanceTimersWrapper`

- package.json
**What**: Temporarily pinning `aria-query` to version 5.1.3.
**Why**: The new version of `aria-query`(5.2.1) was released yesterday and caused a few issues on our end.
Affected issues:
Fixes https://github.com/testing-library/dom-testing-library/issues/1235
Fixes https://github.com/testing-library/dom-testing-library/issues/1238
**How**: Pinning the version in package.json.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)~~
> fix: pin aria-query

- package.json
**What**:
Pin `browserslist` and `caniuse-lite` development dependencies.
Fixes #1242
**Why**:
There has been minor release of browserslist packages that remove support of `op_mob 64` which this library currently makes use of. Updates to the support matrix are considered a breaking change, so by pinning dependencies we can unblock minor and patch changes while pending a major release to update these dependencies and the version support for opera mobile.
**How**:
Added `browsers@4.21.8` and `caniuse-lite@1.0.30001502` to the `package.json` `overrides` object (for Node >=16) and `devDependencies` (for Node 14).
Versions chosen to align with those used in the last commit to `main` on 14 June 2023.
**Checklist**:
~- [ ] Documentation added to the~
~[docs …
> chore: pin browserslist deps

- types/role-helpers.d.ts
**What**:
Increased the TS coverage of the logRoles and prettyRoles functions in the role helpers file,
at the moment cases with `hidden = true` option were not covered.
**Why**:
To further understand the scope of #1201 I've added these defs, I think it's good to have them in the repo.
**Checklist**:
> fix(role-helpers): refine logRoles fn types

- .codesandbox/ci.json
- .github/workflows/validate.yml
Closes https://github.com/testing-library/dom-testing-library/issues/1242
`overrides` is not available in NPM bundled with Node.js 14. But we can hopefully use later NPM versions in older Node.js version.
That way we can keep CI alive without having to make breaking changes.
> chore: Pin NPM version

- .github/workflows/validate.yml
Current Node.js release that will go into LTS next month
> test: Run with Node.js 20

- src/__tests__/wait-for.js
- src/wait-for.js
Cherry-picking https://github.com/testing-library/dom-testing-library/pull/1261 into alpha
> fix: use defineProperty on the error object instead of setting the message directly 

- src/__tests__/wait-for.js
- src/wait-for.js
**What**:
Prevent `waitFor` callback from being invoked even after it resolved, on `waitFor` timeout.
**Why**:
More context can be found [in this issue](https://github.com/testing-library/dom-testing-library/issues/1270), but with that context in mind, it's preventing test side-effects:
`afterEach` should be enough to "clean" the previous test from any side-effect.  However, because of the callback leak issue, `window.variable` will remain to be `123` even after being set back to `1` for a short period of time. 
```js
afterEach(() => {
window.variable = 1;
})
it('my test', () => {
return waitFor(() => {
window.variable = 123;
throw new Error('I want it to timeout');
})
})
```
**How**:
When the clock is mocked, only call `checkCallback` when `finished` is `false` 
**Checklist**:
[docs …
> fix: Stop calling `waitFor` callback after timeout

- .github/ISSUE_TEMPLATE/Bug_Report.md
This PR updates the repro link in our issue template from our old codesandbox to stackblitz.
Resolves #1303
> docs: update reproduction link

- src/__tests__/role.js
- src/__tests__/wait-for-element-to-be-removed.js
- src/queries/role.ts
- src/screen.ts
**What**:
**Why**:
**How**:
**Checklist**:
> chore: Correct some typos and spelling errors

- src/DOMElementFilter.ts
- src/__tests__/pretty-dom.js
Fixes https://github.com/testing-library/dom-testing-library/issues/1191
> feat: Support anonymous custom elements when pretty printing DOM

- src/__tests__/pretty-dom.js
- src/pretty-dom.js
This reverts commit 76cb73dec444fca7ae3d160b4dad3b61f7bc8995.
Fixes https://github.com/testing-library/dom-testing-library/issues/1322
Will reland in https://github.com/testing-library/dom-testing-library/pull/1323
> fix: Revert "feat: Reduce caught exceptions in `prettyDom` (#1321)"

- src/pretty-dom.js
**What**:
We encountered some issues on our CI. We use Azure DevOps with this image: `using docker/cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1`. This was the log produces when a test failed (for a different reason):
```
2) (Site Management) Manage capacity
Permissions
Should show the page when user has correct permissions:
AssertionError: Timed out retrying after 4000ms: Cannot read properties of undefined (reading 'DEBUG_PRINT_LIMIT')
at Context.eval (webpack:///./src/ui/support/page-permissions.helper.ts:25:0)
```
Apparently process was defined, while process.env was not. I don't see the harm to do this extra check.
**Why**:
To have proper error logging when a test fails.
**How**:
I first used patch-package to patch this library on our codebase …
> fix: safer read of DEBUG_PRINT_LIMIT

- src/__node_tests__/pretty-dom.js
- src/__tests__/element-queries.js
- src/__tests__/get-user-code-frame.js
- src/__tests__/log-dom.js
- src/__tests__/pretty-dom.js
- src/__tests__/role-helpers.js
- src/__tests__/role.js
- src/__tests__/screen.js
- src/__tests__/suggestions.js
- src/__tests__/wait-for.js
- tests/setup-env.js
Previous test setup hid legit bugs (e.g. https://github.com/testing-library/dom-testing-library/issues/1322). Now we test `prettyDOM` in each environment (Browser and browser-ish (node+jsdom) on the exact colors by not stripping the ANSI color codes anymore.
> Test highlighting of `prettyDOM` explicitly

- src/pretty-dom.js
Stacked on https://github.com/testing-library/dom-testing-library/pull/1324
Relands https://github.com/testing-library/dom-testing-library/pull/1321 which originally caused https://github.com/testing-library/dom-testing-library/issues/1322
@DavidRieman Could you give this a look if [`3db439b` (#1323)](https://github.com/testing-library/dom-testing-library/pull/1323/commits/3db439bae4f5b4906a9e5849b9e3b86c566007a4) is still matching your original intention?
> feat: Reduce caught exceptions in prettyDom (reland)
