testing-library/dom-testing-library

typings/get-queries-for-element.d.ts

**What**:
Fixes #42 
**Checklist**:

Fix Matcher import path in get-queries-for-element typings; fixes #42

---

.github/ISSUE_TEMPLATE/Feature_Request.md

**What**:
Part of the text was more appropriate for bug reports, and this commit adapts that to feature requests instead.
**Checklist**:

Update Feature Request issue template

---

package.json
src/__tests__/element-queries.js

**What**: upgrade kcd-scripts to latest
**Why**: Something broke with jsdom + jest stuff and the latest kcd-scripts fixes it.
**How**: bump to v0.40.0
**Checklist**:

chore: upgrade kcd-scripts

---

typings/queries.d.ts

**What**:
Add TypeScript declarations for new xxxByDisplayValue functions
**Why**:
Those functions can't easily be used by TS users otherwise
**How**:
Copied + tweaked existing xxxByValue declarations
**Checklist**:

fix(TS): add xxxByDisplayValue TS typings

---

README.md

**What**:
Add browser-monkey to "Other Solutions"
**Why**:
Because readme says "PR if you know other solutions". I know one.
**Checklist**:

Add browser-monkey to "Other Solutions"

---

package.json

**What**:
Upgrade `pretty-format`
**Why**:
To dedupe better and use the latest and greatest version. Also might be useful to get https://github.com/facebook/jest/pull/7125
**How**:
Changed directly on GH 😀 
**Checklist**:

fix: upgrade pretty-format to v24

---

.github/PULL_REQUEST_TEMPLATE.md

**What**:
**Why**:
**How**:
**Checklist**:

docs: add TS to PR checklist

---

.github/PULL_REQUEST_TEMPLATE.md

**What**:
Response to feedback that doc repo is hard to find
**Why**:
**How**:
**Checklist**:

Docs: add link to docs repo in PR template

---

typings/get-queries-for-element.d.ts

This is a follow up on https://github.com/kentcdodds/dom-testing-library/pull/246
**What**:
Make type parameter of `getQueriesForElement` more specific
**Why**:
To provide better type checking
**How**:
By specifying type of queries (same as in [react-testing-library typings](https://github.com/kentcdodds/react-testing-library/blob/master/typings/index.d.ts#L5-L17))
**Checklist**:

Improve getQueriesForElement typings

---

package.json

**What**: Upgrade all deps
**Why**: Closes #234 and Closes #251
**How**: `yarn upgrade-interactive --latest`
**Checklist**:

fix(build): upgrade all packages.

---

src/helpers.js

Oops, this should have been moved in the other one.

fix: Fix coverage report.

---

.travis.yml
package.json

These changes got lost somehow.
**What**: support older Node 10 versions
**Why**: to make the upgrade easier since there doesn't appear to be a hard requirement to use Node 10.18 (see https://github.com/testing-library/dom-testing-library/pull/459#issuecomment-595565564).
**How**: changed `engines.node` from `>=10.18` to `>=10` and updated Travis to use Node.js 10.0.0.
**Checklist**:

fix: support Node >=10

---

src/queries/label-text.js

Copy of #463 which got lost when merging beta into master.

fix(allByLabelText): forEach on NodeList is not supported in edge

---

package.json
src/__tests__/misc.js
src/__tests__/screen.js
src/__tests__/wait-for.js

**What**:
update all the things and get rid of errors
**Why**:
To keep us updated. And because I always do this when I start to do stuff on OSS projects :)
**How**:
`npx ncu -u && npm install && git commit` (and fix some lint warnings)
**Checklist**:
[DefinitelyTyped] (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) N/A

chore: update all the dependencies

---

types/queries.d.ts

**What**: I added a type definition to the `queries.d.ts` file
**Why**: It was missing
**How**: neovim
**Checklist**:
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) N/A?

fix(TS): add `selected` to `ByRoleOptions`

---

package.json

Testing `dom-accessibility-api` canary on https://codesandbox.io/s/testing-library-playground-twms4
Edit: 
Works: https://codesandbox.io/s/caption-and-legend-test-brbjh?file=/src/Component.js. Timing is a bit iffy. I can deal with it though.
**What**:
Consider `<caption>` and `<legend>` for `<table>` and `<fieldset>` respectively
**Why**:
Fixes #570, Fixes #576
**How**:
Bump `dom-accessibility-api`
**Checklist**:
- ~[ ] I've prepared a PR for types targeting
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom)~
- ~[ ] Tests~

fix: Consider <caption> and <legend>

---

src/index.js

**What**: re-export the `getConfig` function
**Why**: So `user-event` can use it to wrap `type` with the `asyncWrapper`.
**How**: update `index.js` to export `getConfig` from `config.js`
**Checklist**:
This is undocumented and using it is not recommended

feat(getConfig): export the getConfig function

---

package.json

**What**: Install TypeScript as a development dependency
**Why**: TypeScript is used implicitly in the `typecheck` script, but is missing from the dependencies, causing an error when running `npm run setup -s` as recommended in `CONTRIBUTING.md`
**How**: `npm i -D typescript`
**Checklist**:

fix(TS): Install TypeScript in development

---

.github/PULL_REQUEST_TEMPLATE.md

**What**: Recommend updating local type definitions
**Why**: It seems like the types have moved back from DefinitelyTyped to this repository, so this repository should be used to maintain them instead of DefinitelyTyped (note that we also may need to remove them to reduce confusion, I'm not sure how though)
**How**: Updated pull request template
**Checklist**:

fix(TS): Recommend updating local type definitions

---

types/suggestions.d.ts

**What**:
Fixing a type definition typo
**Why**:
It appears that in 7f8a15e there was a subtle typo where the lower-case
`testid` was misspelled.
**How**:
I fixed the typo.
**Checklist**:

Fix typo in type definition for suggestions

---

README.md

**What**:
We should link to `/dom` not `/`

docs: link directly to dom docs

---

package.json

**What**:
Closes https://github.com/testing-library/dom-testing-library/issues/940
**Why**:
Following screen-reader implementations. 
**How**:
https://github.com/eps1lon/dom-accessibility-api/pull/629
**Checklist**:

fix: Bump dom-accessibility-api

---

.github/workflows/validate.yml

**What**:
**Why**:
**How**:
**Checklist**:
Checkout: uses Node 16 - https://github.com/actions/checkout/releases/tag/v3.0.0
Setup: uses Node 16 (and removes the versions option, but we're already using the correct option `node-version`) - https://github.com/actions/setup-node/releases/tag/v3.0.0

ci: update actions to v3

---

src/__tests__/element-queries.js
src/queries/text.ts

Resolves https://github.com/testing-library/dom-testing-library/issues/450.
Basically all I did was run the same normalize function that runs later on as part of the errors flow too.
This is a naive solution, I'm more than happy to see if I missed something there :)

feat: enhance byText missing error

---

.github/workflows/validate.yml

Cherry-picking https://github.com/testing-library/react-testing-library/pull/1044

chore: Ensure support for releases from release branches

---

src/event-map.js

typo correction

---

.github/workflows/validate.yml

**What**:
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows.
**Why**:
This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised …

GitHub Workflows security hardening

---

package.json

Closes https://github.com/testing-library/dom-testing-library/issues/1197

fix: Bump used `aria-query` types

---

.github/workflows/validate.yml

Fixes 
> {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
-- https://github.com/testing-library/dom-testing-library/actions/runs/8599893350/job/23563736431?pr=1296#step:8:55
Same as https://github.com/testing-library/react-testing-library/pull/1289/

test: Fix Codecov in CI

---

src/__tests__/events.js
src/event-map.js
types/events.d.ts

**What**:
Add window events "pagehide" / "pageshow" to fireEvent API.
**Why**:
MDN documentation for these events is at:
https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event
By adding these events, it allows library users to use the familiar fireEvent & friends in their test environments to verify pagehide and pageshow behavior.
**How**:
Add the events as entries in `src/event-map.js`.
**Checklist**:

feat: Add window events "pagehide" / "pageshow"
